packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/styles.module.css

> submissions aren't recognizing capital letters (i tried one writing ARRAYS and it rendered as arrays)
Remove the `lowercase` enforced style by scoping `normal-case` (see [TailwindCSS text-transform](https://tailwindcss.com/docs/text-transform#transforming-text)) in a css module and applying it to `ProposalContent` text and its children

bugfix: remove lowercase text transform from proposal content

---

packages/react-app-revamp/pages/contest/[chain]/[address]/rules/index.tsx

> Confusing wording in the contest rules for how does a user qualify to vote
Change the wording in the Rules contest page to ease understanding of how/when a user qualify to vote.

bugfix: rules vote qualification wording

---

packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

Should fix #29 
>  After using the search bar on the View Contests page once, using it again will result in a page that never loads, forcing you to hard reload the page.
Fixes infinite loading when user uses the same contest address in the search form of the contest page by preventing the search function from being called when the contest address in the url is the same as the contest address in the search bar.
Scenario 1: wrong network
1. Go to "View contests" page
2. Type `0x3Aa9538c6aCD23526fF72f75A9b9160a275379C3` in the search bar.
3. After seeing the loader, you should see an error message and a try again button
4. Inputting the same address in the search bar and clicking on 'Search' should give you the same result as **step 3**
5. Change network to 'Polygon'
6. You should see the …

Bugfix 29/searching same address twice infinite loading

---

packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/VotingToken/index.tsx
packages/react-app-revamp/pages/contest/[chain]/[address]/proposal/[proposal].tsx

> UI displays an inaccurate (rounded) value of the user available votes.
Remove `Intl.NumberFormat()` in the current user available number of votes. Sadly, it rounds numbers by default ([see documentation](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)), which caused this bug.
Should fix #23
Pre-requisite: choose a testnet and get some testnet tokens !
1. Go to 'create contest' and go to 'Mint token'
2. Create a token with a max supply of `1`, and pick your address as the receiver
3. Create a contest
4. Go to the contest page
5. Submit a proposal and wait for votes to open (Current state [screenshot](https://imgur.com/a/7JJopeH))
6. Click on the vote button
7. In the input, type a number with decimals (like 0.01)
8. Click on 'Vote!'
9. …

bugfix: inacurate amount of available votes displayed

---

packages/react-app-revamp/components/_pages/ProposalContent/index.tsx

> UI doesn't display proposal content when it has both text and a link to an image
- Get the list of image links with a regex
- map the list of images link and `str.replace` each link with an image tag
- render the proposal content in Interweave
Using contest `/polygon/0xd3eC630A5F86b45418db169fA0AA96283e9925DD`
1. Go the above contest page
2. Wait for the proposals to be loaded
3. You should now see text + images appearing together instead of nothing  in certain proposals
https://imgur.com/Eyp0kBV
https://imgur.com/SH0aWYp
---
| Future improvements: in the future when we integrate with TipTap, the component `ProposalContent` will  be completely reworked to make mixed content less tedious to render.

bugfix: fix image/text not appearing when a proposal content has both

---

packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

> The prompt description is a tad bit too big. It would be nice for it to be smaller and to have a divider.
- Decrease the font size from `md` to `sm` + add a divider (border bottom + padding on the prompt description)
https://imgur.com/LBmNaaE
https://imgur.com/TLz5fME

ux fix: decrease prompt font size & add divider

---

packages/react-app-revamp/hooks/useContest/index.ts

> We are getting rate limited because we are making so many calls to our RPC providers. This PR drastically decreases the number of RPC calls we make on the page where we load a contest.
- Use one RPC call to read all of the proposal data from the Contest contract instead of a call per proposal.

feat: one RPC call to rule them all (instead of one call per proposal)

---

packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx

> In the submit proposal modal, the prompt text is a bit too big and the grey colour is off putting.
- Decrease the font size from `md` to `2xs`
- Change text color to be closer to white 
- Change font-weight to be medium
This way, the prompt description will catch attention less while still being visible enough to the user. 
https://imgur.com/G2bjk5i
https://imgur.com/xHneUkK

uifix: reduce font size in send proposal dialog

---

packages/hardhat/contracts/Contest.sol
packages/hardhat/contracts/governance/Governor.sol
packages/hardhat/contracts/governance/extensions/GovernorCountingSimple.sol
packages/hardhat/contracts/governance/extensions/GovernorSettings.sol

> Add downvoting to the GovernorBravo-derived jokedao smart contracts following the [OpenZeppelin GovernorBravo patterns](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/extensions/GovernorCountingSimple.sol).

feat: add downvoting to smart contracts

---

packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/helpers/isUrlTweet.ts

> We were attempting to render urls as tweets that were not tweets. Closes #44.
- Only render urls as tweet embeds if the proposal is a link to a tweet and nothing more.

bugfix: only parse as embedded tweet if the proposal is just a link to a tweet alone

---

packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

> Allow people to view contests when they don't have their wallets connected.
- Remove unnecessary checks on whether a user is connected for viewing a contest.

feat: allow contest viewing without connecting

---

packages/react-app-revamp/components/_pages/DialogModalDeleteProposal/index.tsx
packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/helpers/isProposalDeleted.ts
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/store.ts
packages/react-app-revamp/hooks/useContestEvents/index.ts
packages/react-app-revamp/hooks/useDeleteProposal/index.ts
packages/react-app-revamp/hooks/useDeleteProposal/store.ts
packages/react-app-revamp/hooks/useSubmitProposal/index.ts
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
packages/react-app-revamp/pages/contest/[chain]/[address]/proposal/[proposal].tsx

- Add delete proposal button on proposal list
- Add delete proposal modal
Scenario 1: contest creator
1. Go to a contest you created
2. On each non-deleted proposal, you should see a delete button
3. Click on the delete button
4. The delete proposal modal should appear
5. If you click on cancel, the modal should close
6. In the delete modal, click on 'Yes, delete'
7.Sign the transaction in your wallet
8. When the transaction is successful, a link to the transaction on the explorer should appear + a go back button
9. Click on go back
10. The modal should be closed. The proposal you just deleted should display 'This proposal has been deleted by the creator of this contest'
11. If votes are still open, voting should be disabled for this proposal
Scenario 2: not the contest creator
You …

feat: delete proposal

---

packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx

>  After submitting a proposal, the UI makes it appear as if the user can submit more proposal when they can't
Possible regression bug.
Should close #50
- use `increaseCurrentUserProposalCount` instead of `setCurrentUserProposalCount` in `fetchProposal` (otherwise the proposal count isn't updated)
- use proper comparisons to determine if the user can submit another proposal : compare  `listProposalsIds.length` and `listProposalsRawData.length` to know if proposals list has finished loading ; if so, if `currentUserProposalCount` < `contestMaxNumberSubmissionsPerUser` and `contestMaxProposalCount` < `listProposalsIds.length`, the user can add another proposal ; otherwise, the button is disabled.
[Video](https://www.loom.com/share/a81a8d59c82f4d9dbbc94108eb3a5a50)
1. Create a contest (in our …

bugfix: fix cap proposal submission check

---

packages/react-app-revamp/pages/contests/live/index.tsx

>  Order live contests by whichever has voting ending first, first.
Closes #52.
- Order live contests by whichever has voting ending first, first.
In the preview you can see that live contests are now ordered by vote end time ascending.

bugfix: render live contests that close sooner first

---

packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/StepIndicator/index.tsx
packages/react-app-revamp/helpers/getContestContractVersion.ts
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx

This PR fixes a race condition I created in [this commit](https://github.com/JokeDAO/JokeDaoV2Dev/commit/582c0ce9523edba5cc90c135441128be90db2bcb) by deleting `setIsListProposalsLoading(true);` in `fetchAllProposals()`.
What has been happening since then is that we try to load a page before we get the necessary data from the RPC endpoints. That explains why the "can't access length of `undefined` error we've been seeing only happens when a ton of people were using the endpoint: when the endpoint isn't getting hammered, proposal data requests return before we attempt to render proposal data, but when it is and latency goes up by even a bit, we try to render data before it loads and errored out (we are attempting to access a member of `undefined` because the proposal data hadn't loaded yet …

bugfix: await loading before rendering proposals

---

packages/react-app-revamp/helpers/getContestContractVersion.ts
packages/react-app-revamp/hooks/useCastVotes/index.ts
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useDeleteProposal/index.ts
packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
packages/react-app-revamp/hooks/useProposalVotes/index.ts
packages/react-app-revamp/hooks/useSubmitProposal/index.ts
packages/react-app-revamp/layouts/LayoutViewContest/Timeline/Countdown/useCheckSnapshotProgress.ts
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

Bug Description: Introduced in #46, the viewing of contests without having a user's wallet connected is only possible on Polygon because that is the chain that the WAGMI library hooks default to if they are not explicitly given a chainId to make calls to (they use the first in the list of chains that they have). This is meant to be possible on any chain that jokedao.io supports.
Fix Description: To fix this, this PR just adds chain information from the url of a link to function calls to get the ABI of a contest as well as those that are made reading contests so that they are run against the correct chain.
- Going to a link contest on a chain other than Polygon ([this one](https://www.jokedao.io/contest/optimism/0x1e4D52b5FfD9Cc8B7c4f5d3c2acCB49E60Da51b6) for example) without one's wallet …

bugfix: access other chains without connecting

---

packages/react-app-revamp/components/FormRadioOption/index.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx

> The submission token value is pre-filled with the previously minted voting token address, which is confusing.
- This PR changes this behaviour and Keep the submission token address value empty if the user picks "Use the same token for both submitting proposals and voting" to avoid confusion
- Align radio inputs on the baseline

bugfix: contest rules creation form inputs

---

packages/react-app-revamp/layouts/LayoutViewContest/VotingToken/index.tsx

- Typo:   Display "your remaining votes" after a contest instead of "Your used votes"
Fixes #56

bugfix#56:  Display "your remaining votes" after a contest instead of "Your used votes"

---

packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/index.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/schema.ts
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts

- Rework `useDeployContest` hook and Form to this:
```
1. anybody can submit (this should be default)
2. only those with voting token can submit
3. require separate submission token to submit
```
Video showcasing the bugfix
https://www.loom.com/share/217ea94f0bb045fbbb2807e689579cc6

bugfix: rework submit proposals options

---

packages/react-app-revamp/pages/contest/[chain]/[address]/rules/index.tsx

* Display 'No submission token for this contest' instead of voting token info when a contest has no submission token
Should fix #82

bugfix: display 'no submission token' 

---

packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/pages/contest/[chain]/[address]/rules/index.tsx

> In contest rules page, this error pops when a wallet isn't connected
* Bugfix: fix rules page displays an error when user wallet isn't connected
This error was due to `checkIfCurrentUserQualifyToVote()` not being called anymore when the user wallet isn't connected. This function calls `contestSnapshot` which returned value is used to set `usersQualifyToVoteIfTheyHoldTokenAtTime`, a variable used in the rules page.
`checkIfCurrentUserQualifyToVote()` is now called even when the current user didn't connect their wallet, and we now prevent `getVotes` from being called if the current user isn't connected (calling it would cause an error).
* Bugfix: display a different message in the callout in rules page if the user wallet isn't connected
* Typo: add a colon in the contest rules form after …

Bugfix: Rules page displays an error when user wallet isn't connected

---

packages/react-app-revamp/components/Button/styles.ts
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step1/index.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/Form.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step4/TextInstructions.tsx

>  Button should say "next" instead of "skip" ; In addition, the "create contest" button should be in bright yellow to encourage users to tap it rather than pressing "skip" And "skip" should be in plain text in a smaller font below "create contest" so that it's not prioritized
- feat: create new button intent ("ghost-neutral")
- bugfix: change step 2 and step 3 skip/next button scale to "sm" and change their intent to "ghost-neutral"
- bugfix: change step 2 and step 3 CTA button from "neutral-outline" to "primary"
- bugfix: fix airdrop step (step 4) bug when user didn't create a contest first
Closes #60

bugfix: change button styles in wizard form steps

---

packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/styles/globals.css
packages/react-app-revamp/tailwind.config.js

- feat: customize `tailwindcss/typography` plugin
- feat: increase the font size of base text in proposals
[x] Styles (UX)
- `/contest/polygonmumbai/0xE4363E04e0d872d96B3611D98fC2f74Bf90f76b5`
- `/contest/goerli/0x71AFb5cD5785825568f9f8ACccd2b00f9aE7A29F`

feat: customize tailwindcss/typography

---

packages/react-app-revamp/hooks/useContest/index.ts

When sorting proposals and their total votes for pagination, include against/downvotes.

bugfix: include against votes in prop sort

---

packages/react-app-revamp/components/_pages/ButtonDownloadContestDataAsCSV/index.tsx
packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/hooks/useExportContestDataToCSV/store.ts
packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts

> Export contest as csv fails after loading 13 proposals
This bug was caused by the pagination. CSV formatting happens in `formatContestCSVData()` which is defined in `hooks/useExportContestDataToCSV` and called in `components/_pages/ButtonDownloadContestDataAsCSV` (we don't load all of the contest data at once anymore but batch by batch, hence why it failed at the 13th proposal since we load proposals 12 by 12).
Now, we ensure that all proposals data are loaded on `ButtonDownloadContestDataAsCSV` mount, and only once all proposals data are loaded (which we track with `isReady` we now `formatContestCSVData()`)  we call `formatContestCSVData()`.
>  if you export a spreadsheet for a contest, it doesn't show the number of votes from each voter per proposal
This bug was caused by the …

bugfix: export contest as csv fails after loading 13 proposals

---

packages/react-app-revamp/components/TipTapEditor/index.tsx
packages/react-app-revamp/components/TipTapEditorControls/index.tsx
packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx

> Some submissions contain images that don’t render. To prevent this, we should add instructions for the image or at least specify “link *must* end in .png or .jpeg”
* feat: add additional instruction `(must end with a valid image extension like .png, .jpeg, .gif ...)` in `window.prompt` of tiptap image extension 
* feat: add to toggle preview in `DialogModalSendProposal`

feat: add file extension reminder to tiptap/image prompt

---

packages/react-app-revamp/hooks/useCastVotes/index.ts
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/store.ts
packages/react-app-revamp/hooks/useContestEvents/index.ts
packages/react-app-revamp/hooks/useProposalVotes/index.ts

> In order to save RPC calls which are costing us a significant amount of money currently we will only update votes live for hour before voting closes on a contest.
Using [`removeAllListeners()`](https://docs.ethers.io/v5/api/contract/contract/) in `ethers` to turn off the monitoring once the voting period is over.
TODO: How can I call `useContract()` like we do `useContractEvents()`, without a provider? (and note - even when I do use `useProvider()` and am connected it still errors saying that the provider is undefined, I think somewhere I'm not plugging into wagmi context correctly)
Also we should use a timer for the time until the vote closes (if we are still in the voting period that is) instead of just an if statement to remove the listeners so we leave nothing to chance (currently …

bugfix: only update votes live for hour before close

---

packages/react-app-revamp/codegen.yaml
packages/react-app-revamp/components/EtheuremAddress/index.tsx
packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/config/links/index.tsx
packages/react-app-revamp/config/urql/index.ts
packages/react-app-revamp/config/wagmi/index.ts
packages/react-app-revamp/graphql/common.graphql
packages/react-app-revamp/graphql/generated.ts
packages/react-app-revamp/graphql/get-default-profile.graphql
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/store.ts
packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/Timeline/Countdown/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
packages/react-app-revamp/package.json
packages/react-app-revamp/pages/contest/[chain]/[address]/proposal/[proposal].tsx
packages/react-app-revamp/services/lens/getDefaultProfile.ts
packages/react-app-revamp/tsconfig.json
yarn.lock

- feat: display Lens profile associated to proposal author/voter Ethereum address if it exists, its associated ENS if it exists, and fallback to the address otherwise ;
- refacto: `useContest` to remove `fetchEns`
**Important**: add `NEXT_PUBLIC_LENS_API_URL=https://api.lens.dev` to your local `.env`

feat: display lens profile

---

packages/react-app-revamp/hooks/useContestEvents/index.ts
packages/react-app-revamp/hooks/useProposalVotes/index.ts

Currently, whether `VoteCast` event listeners are shut off when a contest ends is determined by a race condition on whether `canUpdateVotesInRealTime` or `contestStatus` is updated first. If the former is updated first then the listeners never get turned off, but we want to make sure that regardless of which condition updates first upon the completion of a contest, we disable these listeners as soon as one of them does.
In order to fix this, this PR adds a check to cover when `canUpdateVotesInRealTime` is `false` in the `useEffect`s that control `VoteCast` listeners.
Fixing a bug introduced in #107.

bugfix: remove vote event cutoff race condition

---

packages/react-app-revamp/components/_pages/RewardsWinner/index.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
packages/react-app-revamp/pages/contest/[chain]/[address]/rewards/index.tsx

This PR does 2 things:
- In order for more clarity specifies the percentage that each rank gets paid out when displaying this information to 2 decimals.
- Multiplies the reward amounts by `100000000` to get the number of shares to assign each rank in order to allow 8 decimal places to be entered for reward amounts.

bugfix: allow and render decimals for share and payout amounts

---

packages/react-app-revamp/hooks/useContest/index.ts

* bugfix: only display 'Rewards' in the navigation tabs/sidebar when the contest has a rewards module configured
closes #132

bugfix: dont display rewards tab when no rewards module found

---

packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/components/_pages/RewardsWinner/Reward.tsx
packages/react-app-revamp/components/_pages/RewardsWinner/index.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/store.ts
packages/react-app-revamp/hooks/useContestEvents/index.ts
packages/react-app-revamp/hooks/useProposalVotes/index.ts
packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

* feat: disable event listeners in `useContractEvents` and `useProposalVotes` when the tab isn't focused
* feat: display 'refresh page' banner when user switches tab while realtime votes update is enabled
Demo: https://www.loom.com/share/fa8c53bb5b7e4d0f9c09208bf64306b3

bugfix: Remove event listener on tab isn't focused

---

packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx

Display a help box and do not allow user to deploy the contest if the reward percentages do not add up to 100.

bugfix: ensure that reward percentages equal 100

---

packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts

When we attempt to put the entirety of the proposal content into the excel column, if the proposal is long then it often overflows the column, making the data inconsistent amongst columns and the entire output difficult to read.
By only putting the link to the proposal, there will be consistency to how many characters are in each column and avoid the risk of data overflowing columns.

bugfix: put the link to the proposal as the proposal content as to not overflow columns

---

packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts

With the spaces, this is what the url renders to which just isn't good practice.

bugfix: remove spaces in polygon evm name

---

yarn.lock

Kept getting this warning on the build command `yarn workspace @scaffold-eth/react-app-revamp build`:
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
<span>  Why you should do it regularly: https://github.com/browserslist/update-db#readme</span>
```
and so just ran to get up to date.

chore: update browserslist dependency

---

packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts

Was running into issues with server errors such as "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [https://rpc.sepolia.dev](https://rpc.sepolia.dev)." and server response errors for `eth_getCode` calls for [https://rpc.sepolia.dev](https://rpc.sepolia.dev).
[https://rpc.sepolia.org/](https://rpc.sepolia.org/) is working though!

bugfix: update sepolia endpoint

---

.github/ISSUE_TEMPLATE/bug_report.md

Since we make the Github project public, we'll just have issues auto-assigned there when users create them!

chore: add project to bug report template

---

packages/react-app-revamp/components/_pages/ListContests/index.tsx
packages/react-app-revamp/styles/globals.css

Closes https://github.com/JokeDAO/JokeDaoV2Dev/issues/208
Library `react-headless-pagination` that we use for pagination was causing bullet points to act weirdly around our components, I found a way to define a custom class for tailwind components that we use and removed them.

bug: remove bullet points from pagination in contests

---

packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/index.tsx
packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/useDeployToken.ts

Closes https://github.com/JokeDAO/JokeDaoV2Dev/issues/224
I love the line of thinking where we remove the modal if a user rejects the transaction, that way we do not need to spam users with errors in toast and in modal -- since they just rejected a tx.
But I think that currently, we remove modal in case of any error, I can probably take an hour or two into the next sprint and adjust only removing the modal when the user rejects tx -- otherwise keep modal with error open.

bug: remove modal for minting token if user reject tx

---

packages/react-app-revamp/hooks/useContest/index.ts

Closes https://github.com/JokeDAO/JokeDaoV2Dev/issues/218
The code duplication issue in the `useContest` hook, specifically when indexing a non-existent contest, has been resolved. This PR aims to remove the redundant code to maintain codebase cleanliness and efficiency.

bug: remove duplication of code in useContest hook

---

packages/react-app-revamp/hooks/useProposal/index.ts
packages/react-app-revamp/hooks/useUser/index.ts

If you go to the latest jokerace deployed on zkRollup and you are not connected with a wallet, the proposal won't load and error will come in.
This is some weird behavior from `useNetwork` hook, it treats these chains as undefined, therefore also to keep consistent, let's retrieve chains from `config/wagmi` like in other components.
URL to trigger error - https://www.jokedao.io/contest/polygonzkmainnet/0x6954FCfB44bb24B5fD51B8A96ABbd9E84eD5cAEd

bug: use chain list defined in config/wagmi instead of network hook

---

packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

We discovered a mobile bug that was posted in our TG group, when the user scrolls through the proposals page, the contest status is not fixed on top.
https://user-images.githubusercontent.com/18723426/229784769-c8be26f2-298e-474a-8a94-f45fa3d67fce.mov

bug: contest status floating on proposals page

---

packages/react-app-revamp/hooks/useContestEvents/index.ts
packages/react-app-revamp/hooks/useProposalVotes/index.ts

This PR addresses app errors caused by fetching ENS names in non-supporting networks.
Exception handling has been improved by wrapping `fetchEnsName` calls in try-catch blocks. In cases where ENS is unsupported, the ETH address is utilized directly, ensuring app functions across diffrent networks.
I'm logging it for now so i can see in console tomorrow if this is the case!

bug: add try/catch for fetching ENS name

---

packages/react-app-revamp/pages/index.tsx

I've initially liked opacity animation on landing of a text under header and stages, however i feel like it is redundant since contests are animating below, also when you land on that info automatically appears while contests are loading.

refactor: remove fade in animations from landing

---

packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx

Fixes issue where .eth is appended to the end of addresses.
Example contest: contest/celotestnet/0x003dA13b325cBa4d4477207871d8E7C7F2F5AD8E.
Old:
New:

typo: remove incorrect .eth suffix

---

packages/react-app-revamp/components/_pages/Create/utils/csv.ts

We will revert once we successfully support, but right now while we are troubleshooting decimals, we are disabling them.

bug: disable decimals for now

---

packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx

Think this would be helpful to change as it could be confusing because the first load does not, in fact, give the top voters, so people might be confused/make incorrect assumptions about who the top voter on a proposal is without loading more.
I also don't think we should sort proposal voters for the same reason: we don't want people to get the false impression that a person who happens to be the highest voter of the first batch pulled for a proposal is in fact the highest voter for then whole proposal (in the case that multiple loads are required to get all of the voters for a proposal).

chore: rename top voters to voters to avoid confusion

---

packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx

Currently, the entire URL is displayed rather than just the contest name in the URL's head.

bug: contest title is not showing in the head of URL

---

packages/react-app-revamp/config/wagmi/index.ts

Removing because there's no real good reason you'd want to make a contest on mainnet but a ton of downside if people accidentally deploy to mainnet (costs hundreds of dollars), so removing option for now.

chore: remove mainnet as an option

---

packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

Closes #364 - @NakedFool does this look like the right (and more importantly comprehensive, don't want to change this and then other parts of the frontend rely on it to be something else) fix for this bug? 
The bug is when the user doesn't have a connected wallet, it doesn't include a chain name in the Twitter shared url - and even when people are connected, it capitalizes the first letter for some reason.

bug: look at chain name in url for share links

---

packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
packages/react-app-revamp/hooks/useCastVotes/index.ts
packages/react-app-revamp/hooks/useUser/store.tsx

First i've wanted to disable voting widget until votes has been deployed successfully or caught in error, but not ideal UI/UX approach.
We shouldn't really disable slider and input in voting widget when votes are deploying, in case you want to prepare yourself at other proposal to vote, only button should be disabled!

bug: add optimistic approach for voting popup cast votes and available amount

---

packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/index.tsx
packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
packages/react-app-revamp/helpers/tokens.ts
packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
packages/react-app-revamp/hooks/useFundRewards/index.ts
packages/react-app-revamp/hooks/useRewards/index.ts
packages/react-app-revamp/hooks/useTokenBalance/index.tsx
packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
packages/react-app-revamp/lib/contests/index.ts
packages/react-app-revamp/styles/globals.css
packages/react-app-revamp/tailwind.config.js

Closes #380
Closes #379
Closes #372
This PR addresses the UI/UX and codebase polishing of a rewards module.
**UI/UX changes:**
-  We had an error with resolving tokens that are any decimal besides standard 18 decimals, we now successfully distribute and withdraw them. Reading those values is now different as well, we are now displaying exact amount of decimals if needed ( for example 0.00069 $ETH ) 
- We are no longer showing erc20 tokens in contests table if there are no rewards, example was on polygon we would show 0 $WMATIC if there isn't any token in a pool.
- Modal for checking balances is now more intuitive, if token is already in a list we do not proceed with adding it, otherwise we have 2 options, 'add' and other one is 'withdraw' that only applies to the creator.
- Previously in …

feat: rewards module ui/ux & code polish

---

packages/react-app-revamp/hooks/useContest/index.ts

Fixed the rendering of `totalVotesCast` on load, but for some reason it still doesn't work correctly on the vote event (I had to reload the page).
Update: nevermind, #393 fixed the issue with vote events not updating it! All is good!

bug: fix totalVotesCast check

---

packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

The Submit button was not showing up on [this contest](https://jokerace.xyz/contest/optimism/0xA7C5d11Fd92c528665406471eC38B625D9a1F075) and it turns out that if the `msUntilNext` variable is too big, the timeout just executes immediately. And because there is a 1 month gap between the beginning and end of the submission period, the timeout was executing immediately, making the frontend think that voting was open!
Fixing for now by capping at 100,000,000 ms for max timeout, but we can change if we need to!

bug: timeout fails if too many milliseconds, so just cap max timeout

---

README.md
packages/react-app-revamp/README.md
packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
packages/react-app-revamp/config/wagmi/custom-chains/polygonMumbai.ts
packages/react-app-revamp/config/wagmi/index.ts

This PR refactors how we implement RPC providers to allow us to be much more declarative and flexible in what providers we choose to use for which chains, and further, how we want to handle cases where environment variables aren't provided or RPC providers fail/fallback strategies.
I added in our Alchemy provider for Polygon, Optimism, and Arbitrum, and otherwise we just use public endpoints. I added these env vars in Vercel so when we merge it should all be good to go for a smooth transition.
Note: the naming of the networks is just lining up with what we had before and what we thus have in the db so that things are backwards compatible.
We're going to make a way in #359 to set which chains we want to provide live updates for because trying to get live updates on a chain through a …

chore: refactor chains to be explicitly defined

---

packages/react-app-revamp/components/Share/index.tsx
packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/store.tsx
packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/Tabs/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
packages/react-app-revamp/lib/contests/index.ts

This PR addresses the UI/UX issues on the contest page.
**UI/UX Issues fixed:**
- added rewards info next to contest creator address in contest page
- fixed voting popup to not close after you click on button, now we await for tx to be success and close it then ( this actually wasn't a bug but feature from me, i was initially thinking it is good to automatically close voting popup as you can move on and look at others, however it might be better for user to leave that option if they wanna close it or not )
- contest creator address in contest page wasn't shortened before, now we follow same pattern of shortening and added a click event to go to explorer
- When it comes to skeleton loading through all site, maybe it is not the best idea to load skeletons on the contest page as there is a …

feat: cosmetics updates

---

README.md
packages/react-app-revamp/README.md
packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
packages/react-app-revamp/config/wagmi/index.ts

Because alchemy api key goes to all alchemy supported chains apparently.
Super weird Alchemy dashboard setup that makes you choose a chain to make your project on but then the API key it gives you works on all chains - I was confused by this and thought you needed one for each chain you wanted to use Alchemy for. Tis not the case.
So rolling back some of the changes in #402 bc it is apparently not that deep at least wrt how many env vars you need.

chore: remove extra provider env vars

---

packages/react-app-revamp/components/Voting/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableRow/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionDate/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableBody/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Recipients/index.tsx
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/layouts/LayoutViewContest/Prompt/index.tsx
packages/react-app-revamp/styles/globals.css

**UI/UX cosmetics included in this PR**
- keyboard events for voting & submission popup are now active
- calendar dark mode format is done
- on the allowlist pages in create flow, we now have placeholders for voting & submission preview box
- voting/submission times were 1 min behind, not 1 minute specifically but 1s
- when you interact with input when setting percentages during creation of reward pool, 0 was always there and was messing up with UX.
**Separate issues**
- resolving ENS, is this something that we still have to configure from alchemy dashboard so it doesn't use polygon always? @seanmc9 
- sort all proposals for a filter (live, upcoming) and not just the ones on the current page ( this should be it's own PR as it needs small refactor )
-  view all contests should default to …

feat: cosmetics update

---

packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx

Users are reporting broken images over at https://jokerace.xyz/contest/polygon/0x8F99798D17c9DF10fd205E5D696f1F327Ce3DabF
Some of these broken images aren't actually a valid source as they provided a folder link, however, let's make a small adjustment and whenever link is broken, show source in the paragraph so at least it can lead user to a either img or folder like it was a case with some.

bug: fix broken images

---

packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/helpers/formatNumber.ts

This PR updates the ranking system for proposals to handle ties in vote counts more effectively. Previously, the rank was derived directly from the index in the sorted list, which resulted in incorrect rankings when there were ties in vote counts.
Additionally, our `formatNumber` fn was using floor so we do not round a number, but it impacted lower numbers. Since we are now rounding all votes to a 4 decimal, there isn't a need to format a number rather than to american numbers, since it will not affect UI.

bug: fix rank in proposals and do not floor vote number in formatNumber

---

packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
packages/react-app-revamp/config/wagmi/custom-chains/polygonMumbai.ts
packages/react-app-revamp/config/wagmi/custom-chains/polygonZkMainnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
packages/react-app-revamp/config/wagmi/index.ts

Wagmi's Alchemy RPC hook wasn't working correctly for some reason, so just moved us to custom chain configs and stuff's working now (not routing to public rpc endpoints which ratelimit us when they should go to Alchemy ones).

bug: remove alchemy rpc hook, just use custom configs

---

packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts

- OP's self-hosted mainnet RPC sucks, moving to Ankr's for our public one
- Arbitrum One's testnet public RPC was just an incorrect copypasta so fixing that

chore: update OP RPC to ankr so not being rate-limited, correct Arb testnet

---

packages/forge/test/RewardsModule.t.sol

This case should return the error `"RewardsModule: there are not enough proposals for that ranking to exist, taking ties into account"` because there isn't a 2nd ranking, everything's just tied for 1st.

test: 2 props, no votes, pay out 2nd

---

packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts

https://rpc.sepolia.org/ was erroring out, this new one works though!

chain: update sepolia rpc provider

---

packages/react-app-revamp/config/wagmi/index.ts

Public nodes are being used as a backup by the app, however they also cause a CORS problem, which stops production for chains with alchemy setup.

bug: remove public node fallback for alchemy chains for now

---

packages/react-app-revamp/components/Rewards/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestRewards/index.tsx
packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
packages/react-app-revamp/hooks/useDeployRewards/index.ts
packages/react-app-revamp/hooks/useDeployRewards/store.tsx
packages/react-app-revamp/hooks/useFundRewards/store.tsx
packages/react-app-revamp/hooks/useRewards/index.ts
packages/react-app-revamp/hooks/useRewards/store.tsx
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
packages/react-app-revamp/pages/contest/new/index.tsx

Closes #460
- We are now allowing users to opt out of rewards modal during deployment after contests is created.
- When user is funding pool, we are always getting rewards address directly from chain.

bug: allow opt out of deploy rewards modal and query rewards address when funding pool

---

packages/react-app-revamp/components/Parameters/index.tsx
packages/react-app-revamp/components/Voting/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
packages/react-app-revamp/helpers/parseVotingCsv.ts
packages/react-app-revamp/hooks/useCastVotes/index.ts
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/store.tsx
packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
packages/react-app-revamp/hooks/useGenerateProof/index.ts
packages/react-app-revamp/hooks/useProposalVotes/index.ts
packages/react-app-revamp/hooks/useSubmitProposal/index.ts
packages/react-app-revamp/workers/generateProof.ts
packages/react-app-revamp/workers/generateRootAndRecipients.ts
packages/react-app-revamp/workers/parseSubmissionCsv.ts
packages/react-app-revamp/workers/parseVotingCsv.ts

Closes #455 
The following changes have been made as part of this PR, and i'll compare the before and after changes here:
**Before**
- In the past, we generated a merkle tree as the contest loaded, specifically after the contest and after user qualifications, but loading in that way caused the browser to lag or freeze when we attempted to generate more than ~ 60k allowlists in the browser.
- In the create flow, we have to generate a tree during a step for voting or submission ( in case allowlisted ) so in case of an error, user can't proceed to the next step, while this logic is good, we can't do it in browser in case of a bigger dataset.
- Hook for generating a proof while it was simple, it needed a bit of refactor. 
**After**
- We only generate the combined merkle tree and proof when a …

feat: add workers to generate merkle tree and proof for submission/voting & create flow

---

packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
packages/react-app-revamp/components/UI/Markdown/components/MarkdownOrderedList/index.tsx
packages/react-app-revamp/components/UI/Markdown/components/MarkdownText/index.tsx
packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
packages/react-app-revamp/styles/globals.css

Closes #478 
This PR includes following:
- We are now preventing overflow on any kind of content, previously it was applied to children instead of parent.
- Code for markdown is a bit better organized and structured.
- In a preview box, we are also displaying up to 3 list items, since we can't prevent it otherwise just based on text characters length.
- Added custom numbers for ordered list.

bug: fix formatting issues, refactor and organize markdown code, prevent more than 3 list items in a preview box and add custom order numbers

---

packages/react-app-revamp/components/Voting/index.tsx
packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

Closes #499
This PR includes following: 
- We are not reloading complete page when user is attempting to change network in a wallet.
- We are only requiring network change when user tries to either submit or vote.

chore: remove change network banner in contest page, and add switch network options on submit & vote

---

packages/react-app-revamp/hooks/useAccountChange/index.tsx
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/store.tsx
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

Closes #503 
This PR includes following:
- We built a custom hook called `useAccountChange` that watches for account changes and put it in the hooks section so it may be reused if needed in the future.
- When a user switches accounts, we are now displaying the right qualifications because we are listening for these changes in the contest layout.

bug: reload user qualifications when acccount is changed

---

packages/react-app-revamp/layouts/LayoutViewContest/Prompt/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx

We just need to apply `prose-invert` class along with `prose` class so colors aren't inherited with prose.
Example is last proposal from this contest https://jokerace.xyz/contest/lootchain/0x1041cF51444cDaC8918514c5E1C97343200580a0
You can see that the titles are in dark-blue, this PR includes a fix for the above!

bug: add prose-invert class to all prose classes

---

packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/store.tsx
packages/react-app-revamp/hooks/useContest/v3/contracts.ts
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

This PR solves a bug that was introduced by yesterday PR for the R2 stuff.
It is no biggie in terms of codebase change, the only thing i've noticed is when you aren't connected and try to connect, wrong qualifications are displayed, and this was because i've refactored yesterday hook ( which is good refactor ) but forgot to set roots in the store.
Now because i really don't want to relay on store for these kind of info which are easily fetchable from the chain ( roots ) and it is better if we always fetch for these when we need them rather than passing around in the zustand.

bug: remove roots from contest store

---

packages/react-app-revamp/hooks/useContest/v3/contracts.ts

Currently we are still fetching for `submissionMerkleRoot` and `votingMerkleRoot` in the `readContracts` call when we are loading the contest.
It isn't needed anymore as it is handled afterwards.

chore: remove merkle root calls from contracts v3

---

packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx

Using `Link` component from next in order to route user in the app to the submissions.
Reason for this is as previously what i assumed was an discrepancy in the `getStaticProps` but after reading a little bit more and talking in discord, this function is **only** called during build-time in the production. While in dev mode, it is called always.
So actually, a call that was awaited was only fetching of the page html, and `Link` provides a prefetch by default as long as cards are in the viewport!

chore: update navigation to use link so it can use prefetch method for submissions

---

packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
packages/react-app-revamp/helpers/parseVotingCsv.ts
packages/react-app-revamp/hooks/useDeployContest/index.ts
packages/react-app-revamp/lib/vip/index.ts
packages/react-app-revamp/supabase_schemas/user_permissions.sql
packages/react-app-revamp/workers/parseSubmissionCsv.ts
packages/react-app-revamp/workers/parseVotingCsv.ts

Closes #542 
In this PR we are adjusting codebase for jokerace vip programme and we did following:
- We added a file only for current and future calls upon `user_permissions` aka vip table
- We are now only checking for the allowlist size during either parsing a voting csv, submission csv or when user is trying to deploy a contest.

feat: add functionality for jokerace vip programme

---

README.md
packages/react-app-revamp/README.md
packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx
packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
packages/react-app-revamp/hooks/useUploadImage/index.tsx
packages/react-app-revamp/lib/image/imgur/index.tsx

Closes #567 
In this PR we are implementing following:
- We added a `useUploadImage` store that will handle upload of all images based on services we are providing
- For now we are hardcoding `imgur` as a service since we do not support other implementations
- All business logic is extracted in the store itself, we only need to provide file args in the UI components
- We have file upload from PC and as well drag & drop upload from PC
- We are currently limited to **12,500 requests per day** for free tier, however, if in future we start to generate revenue, we would need to signup for commercial usage
- Added `NEXT_PUBLIC_IMGUR_CLIENT_ID` as an env variable only locally for now, we do not need secret id as we are posting anonymously these images, however created one from jklabs email, …

feat: add functionality for image upload and append modularity for future implementations

---

packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
packages/react-app-revamp/hooks/useCastVotes/index.ts
packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
packages/react-app-revamp/hooks/useFundRewards/index.ts
packages/react-app-revamp/hooks/useSubmitProposal/index.ts
packages/react-app-revamp/hooks/useUser/index.ts
packages/react-app-revamp/lib/analytics/participants/index.ts
packages/react-app-revamp/lib/analytics/rewards/index.ts
packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql

Closes #362 
In this PR we are adding an internal analytics system so we can track how many times each user has either voted or submitter on contest and on the other side if contest has rewards, we are tracking tokens that are being deposited or distributed.
Codebase changes:
- I've added under `lib` folder a new folder called `analytics` which as 2 subfolders `rewards` and `participants`
- In each folder we are implementing a business logic for getting, updating or inserting rows into those tables
- We are tracking events on submit a proposal, vote on a proposal, deposit into the rewards pool or distribute from the rewards pool

feat: add participants and rewards internal analytics components

---

packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx

This reverts commit 17a67d5bed3a00c930494a23ea8f6d9f29d2c7af because it is causing a bug where, if you're logged in with an account that isn't allowlisted, it displays the text saying that submissions are not open.

bugfix: revert #586

---

packages/react-app-revamp/lib/contests/index.ts

We were checking the submissionMerkleTree column in supabase which has been deprecated, so it was always returning null aka that everyone is allowlisted, which was erroneous for contests that actually do have submission allowlists.

bug: check subMerkleRoot instead of deprecated subMerkleTree

---

packages/react-app-revamp/lib/contests/index.ts

I incorrectly updated the check for this in #593 and that was resulting in searching erroneously saying that people were not allowlisted to submit for contests that are open for anyone to submit to, so just fixing here.

bug: correctly check submission root

---

packages/react-app-revamp/components/Parameters/index.tsx

Smol grammatical fix. Currently at [this contest](contest/base/0x037Bfb31d1f656b42aB6aCA506dFed5272914561), the limit is 2 submissions per user but this is what it's currently saying.
Should be "2 submissions" and this PR fixes that.

wording: use plural for submissions if applicable

---

packages/react-app-revamp/helpers/getContestContractVersion.ts
packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
packages/react-app-revamp/helpers/timeout.ts

Closes #677 
So it looks like this one was a more of a broader issue than related to the rewards only and i'll try to explain here.
If one of the RPCs are hanging, in our codebase, `version` wouldn't be resolved and since it doesn't return in error but rather in hang state, we couldn't resolve it with try / catch here.
Initially i wanted to call some other functions on `provider` and check if RPC is alive, but if RPC is unresponsive, it just hangs rather than error out.
Therefore we have to add a little hack here and it is up to us to set a max amount of time we want to wait for RPC to be responsive, and using `Promise.race` we are checking which will first be executed, if everything is successful it will always race over that timeout that we set, otherwise, it would hang for in our case …

bug: add timeout for unresponsive RPCs

---

packages/react-app-revamp/components/Share/index.tsx

Just some small thing that i've noticed and wanted to push it, icons aren't same size in the share dropdown, this happened when i replaced Lens logo.

bug: icon sizes aren't equal in share dropdown

---

packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/base.ts
packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
packages/react-app-revamp/config/wagmi/custom-chains/celo.ts
packages/react-app-revamp/config/wagmi/custom-chains/celoTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
packages/react-app-revamp/config/wagmi/custom-chains/evmosTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/lukso.ts
packages/react-app-revamp/config/wagmi/custom-chains/luksoTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/mantle.ts
packages/react-app-revamp/config/wagmi/custom-chains/mantleTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/qChainTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/roninTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/scrollSepoliaTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
packages/react-app-revamp/config/wagmi/custom-chains/zetaTestnet.ts

the link to the rewards module address for contests who have one and are on a chain that doesn't have an ending slash at the end of their block explorer url in the chain config like mantle (and this contest on mantle) was failing and going to
`https://explorer.mantle.xyzaddress/0x9D7e68621311a88f7f44d78b652D3e027fE4D718`
instead of the correct url of
`https://explorer.mantle.xyz/address/0x9D7e68621311a88f7f44d78b652D3e027fE4D718`.
this PR fixes this issue for our mantle config as well as others that were missing this slash.

chain: add ending slashes to block explorers

---

packages/forge/test/Contest.t.sol
packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useProposal/index.ts
packages/react-app-revamp/hooks/useSubmitProposal/index.ts

chore: bring back version param, tests, and fetchSingleProposal from #663

---

packages/react-app-revamp/helpers/timeout.ts

was timing out on calls to mantle's testnet, so need to bump

chore: increase time to wait for rpc to 10s

---

packages/react-app-revamp/helpers/getContestContractVersion.ts
packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts

Should come after #734.
for efficiency given the most likely scenario on average (a user will be getting the latest or one of the most recent versions).

chore: reorder fe versions

---

package.json
packages/react-app-revamp/package.json
yarn.lock

just a regular update of next and turbo libraries.
motivation is that I got an email from Next talking about the improvements esp to `next dev` that come with 13.5, so wanted to upgrade there. here's the [link](https://nextjs.org/blog/next-13-5?utm_source=marketo&utm_medium=email&utm_campaign=monthly_newsletter) to the announcement - some cool stuff!
and then also just locally was getting told that there was a new version for turbo, tried it, and it literally cut build time in more than half from 26s to 12s.

chore: update next and turbo libs

---

packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
packages/react-app-revamp/config/wagmi/index.ts

wagmi's default mainnet provider was cloudflare-eth.com, and ever since we have moved over to cloudflare that has been causing very weird and intermittent problems when we are trying to call `fetchEnsName`, so we are explicitly setting our own config for mainnet.

chain: make explicit mainnet config

---

packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts

Closes #794 
we just needed to add the necessary config information for mainnet to be able to resolve ENS information. got it from the official wagmi package [here](https://www.npmjs.com/package/@wagmi/chains?activeTab=code).

bugfix: add mainnet ENS resolver config

---

packages/react-app-revamp/lib/user/index.tsx

we don't need to do this because if users try to go to the submission will just show as "this submission has been deleted" anyways, and we don't want to do it because it slows down query times.
removes logic implemented in #814.
context for why we started collecting this data in the first place is just for analytics to be able to answer questions like "how many vote txns were cast on proposals that ended up being deleted in the past month?".

chore: don't filter deleted submissions from user profile results

---

packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx

bugfix: prevent 404 on older contests if no metatags

---

packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
packages/react-app-revamp/lib/permissioning/index.ts
packages/react-app-revamp/workers/nftOwnersProcessing.ts

I've noticed a bug in `submission` tab when creating a contest, if you set up voters to be submitters as well, while merkle root is the same, we didn't hardcode 10 votes per address as we need for submitters.

bugfix: voters same requirements

---

packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx

Just a small visual bug, on desktop there is unused space between prompt and creator when there is only one proposal, while on mobile, container with borders is visible when there is only one proposal

bugfix: hide submission navigation containers if there is only one submission in contest

---

packages/react-app-revamp/config/wagmi/custom-chains/qChain.ts

MM was erroring with this when I tried to switch chains, looks like the currency symbol needs to be between 2 and 6 characters.

chore: update q currency name

---

packages/react-app-revamp/lib/monetization/index.ts

chains with names containing multiple words like publicGoodsNetwork or polygonZk weren't populating as having entry fees enabled because the frontend wasn't parsing the info from the db correctly.

bugfix: check lowercase chain names for entry charge

---

.github/workflows/auto_merge_main_PRs.yml
.github/workflows/auto_rebase_main_PRs.yml

add an automation to keep staging synced up with main whenever we merge into main.
when we merge into main from staging in our current flow, a merge commit is created, and that merge commit needs to be merged into staging for staging to be kept up to date with main. this workflow automates that.
tested in #906, #907, #908, #909, and #910
inspo from https://medium.com/@karlstad/create-a-github-actions-workflow-that-auto-merges-the-master-back-to-dev-branch-8b1ebe7009b3

chore: add gh action to auto-merge main PRs into staging

---

packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx

bugfix: only show parenthesis in params if permissioning requirements

---

packages/react-app-revamp/lib/gtag/index.ts
packages/react-app-revamp/package.json
packages/react-app-revamp/pages/_app.tsx
packages/react-app-revamp/pages/_document.tsx
yarn.lock

Closes #918
Implementation of it was followed by nextjs guide of how to implement google analytics as we can't just add script tag, because we need to follow route changes to achieve correct tracking.

feat: add google analytics to frontend

---

packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx

Negative margin was applied to the div that surrounds editor controls, so i removed it.

bugfix: remove negative margin on editor controls

---

packages/react-app-revamp/lib/contests/index.ts
packages/react-app-revamp/pages/user/[address]/index.tsx

Ugh this one was kind of stupid and not sure how i didn't test this before, but basically we only had `profileAddress` when checking for qualifications on the user page, so, by visiting any profile page, you would actually qualify for all the contests they have created.

bugfix: user page incorrect qualification

---

packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
packages/react-app-revamp/package.json
yarn.lock

Since there is no window object in SSR `window.location.href` can't be used and `useRouter()` hook is available on the client side only.
Therefore we need to add this package that will use full URL when on contest page so we can auto-populate it in github.

enhancement: add bug report link in broken url or rpc page

---

packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/hooks/useProposal/index.ts
packages/react-app-revamp/hooks/useProposal/utils.ts

Implemented a new utility function `updateAndRankProposals` for dynamic ranking of proposals on updates/deletions. Adjusted proposal count logic to accurately reflect changes when proposals are deleted.
There are 3 key changes here:
- New utility function recalculates rankings upon proposal updates or deletions.
- Accurate submission count: `submissionsCount` now updates correctly when proposals are deleted.
- Modified to use `submissionsCount` for determining if more proposals are available to load.

bugfix: add utility fn to update proposal rank

---

packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/hooks/useProposal/index.ts

This PR addresses an issue where switching tabs caused duplicate proposals to appear due to repeated calls with the same `listProposalIds` 
We integrated `fetchProposalsPage` to be called at the end of `fetchProposalsIdsList` since that function is being called only when you switch contests.

bugfix: call fetch proposal page in hook

---

packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx

Closes #993 
When the user switches to the timing tab, we just set the submission open date to the current date. This is because, even if we advise doing so immediately, if you spend any time on any other tabs before the timing tab, it won't be current, so we need to reset it so the user doesn't have to.

bugfix: remove contest timing reset when it is not current time

---

packages/react-app-revamp/helpers/timeout.ts
packages/react-app-revamp/hooks/useCastVotes/index.ts
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContestEvents/index.ts
packages/react-app-revamp/hooks/useProposal/index.ts
packages/react-app-revamp/layouts/LayoutViewContest/index.tsx

Closes #1053 
This bugfix includes fix to 2 issues. The first issue is why live vote updates was allowed in the contest, despite though there are about ~29 days remaining to vote (we should only let people vote in the last two hours). 
The reason real-time voting updates were allowed in that contest is that `setTimeout` has a maximum delay value of 24.8 days or 2,147,483,647 ms. This leads to integer overflow, which causes the timeout to be executed immediately, see [here](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value)
The second problem was that when we used the cast vote listener for realtime voting, the update proposal have received an empty list of all proposal data, which led to mapping over an empty array (which is why the warning appears).

bugfix: add max delay for timeout and adapt live vote

---

turbo.json

with our flow of squashing we almost never hit the cache, so we don't have remote caching turned on in Vercel. also, caching locally exceedingly rarely ever hits because it would have to be a build with no changes, so locally it doesn't provide upside, but does cause some significant bloat in repo size over time. it also slows down builds both locally and in Vercel due to compiling and storing the cache.
so we're just disabling it here.
for reference: what it looks like in vercel + the extra time per build it adds.

chore: disable turbo caching bc we don't use it

---

yarn.lock

Removes this warning in the build. Just ran `npx browserslist@latest --update-db` and it updated yarn correctly.

chore: rm update db build warning

---

packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx

I saw that on https://jokerace.xyz/contest/unique/0xf905aF366b5a7C14B514CB523b40CA5C4be7f3EB if you try read more and read less, on the first time, prompt is not expanded fully due to incorrect calculation of max-height.
I figured out and it is best practice, to set that max-height to 999em and not worry about it!

bugfix: remove max-height on contest-prompt

---

packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
packages/react-app-revamp/lib/proposal/index.ts

used single quotes for `compareVersions` import in #1110 and just fixing to make formatting cleaner and consistent.

fmt: use double quotes

---

packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx

Just a small visual bug on mobile, comments section should be below voting widget in proposal.

bugfix: display comments section below voting widget in proposal on mobile

---

packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx

Closes #1117 
Lens was returning a Profile that had a ProfilePictureSetFragment but not a handle, so we were getting a weird outcome as shown in the ticket. In this PR, we make it so that we only use the Lens return if it returns a handle.

bugfix: check for lens handle

---

packages/react-app-revamp/next.config.js

Was getting the complaint that Vercel wasn't able to pre-cache again [here](https://vercel.com/jokerace/jokerace/ADJxzRfgASjSFtxdLFGRPF4wAyTq) so just bumping to hopefully solve it for a while.

chore: bump maximumFileSizeToCacheInBytes to 10mb

---

packages/react-app-revamp/hooks/useContest/index.ts
packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts

I have noticed that is is better to fetch for merkle roots in the batch when we fetch contract data results, since we can invoke process user qualifications fn immediately after it.

chore: invoke process user qualifications immediately after contract results

---

packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
packages/react-app-revamp/components/_pages/Submission/index.tsx
packages/react-app-revamp/lib/proposal/index.ts
packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx

`parseFloat("4.20")` was returning 4.2 instead of 4.20, which would mean that our frontend would think that the contracts for contests like [this boi](https://jokerace.xyz/contest/optimism/0xD610D18d3B3c0eeFF64F0aD54D0b4f3f8A0Bde02) and [this boi](https://jokerace.xyz/contest/arbitrumone/0x3e3770C3838aad94AE5784509c0A45016795A36f) were not high enough of a version to support comments even though they in fact were.

bugfix: use version as string for proposal page

---

packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Voting/index.tsx
packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
packages/react-app-revamp/lib/permissioning/index.ts

I've noticed that we can use Arbitrum now retrieve the owners of NFT collections with Alchemy API.
To enable us to pass `arbitrumone` for the variables but maintain `arbitrum` as the label in the dropdown, i also refactored a dropdown to accept both value and label so we do not need to add those additional checks. This also applies to `ethereum` and the `mainnet`.
EDIT: I minted an NFT on Arbitrum 10 days ago, so i'm going to spin a contest to see how the community reacts :]

enhancement: add arbitrum chain to nft requirements

---

packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx

For some reason, the `onChange` handler was removed from the input change during the refactoring in #1257, which prevented you from adding your own types and only accepted our predefined ones.

bugfix: add onChange to input change in contest type

---

packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/astriaDusk2.ts
packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
packages/react-app-revamp/config/wagmi/custom-chains/base.ts
packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/berachainTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
packages/react-app-revamp/config/wagmi/custom-chains/frameTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
packages/react-app-revamp/config/wagmi/custom-chains/holesky.ts
packages/react-app-revamp/config/wagmi/custom-chains/neonDevnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/proteus.ts
packages/react-app-revamp/config/wagmi/custom-chains/redstoneHolesky.ts
packages/react-app-revamp/config/wagmi/custom-chains/ronin.ts
packages/react-app-revamp/config/wagmi/custom-chains/roninTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
packages/react-app-revamp/config/wagmi/custom-chains/x1Testnet.ts
packages/react-app-revamp/config/wagmi/index.ts

In this PR, the default logo for any chain for which we do not currently have a logo is mona lisa.
If we don't currently have a logo, all we have to do is apply `/contest/mona-lisa-moustache.png` to the `iconUrl` property when we add chain later on.
Example here:
```
export const artheraTestnet: Chain = {
id: 10243,
name: "artheraTestnet",
network: "artheraTestnet",
iconUrl: "/contest/mona-lisa-moustache.png",
nativeCurrency: {
decimals: 18,
name: "Arthera",
symbol: "AA",
},
rpcUrls: {
public: { http: ["https://rpc-test.arthera.net"] },
default: { http: ["https://rpc-test.arthera.net"] },
},
blockExplorers: {
etherscan: { name: "Arthera Testnet Scan", url: "https://explorer-test.arthera.net" },
default: { name: "Arthera Testnet Scan", url: "https://explorer-test.arthera.net" },
}, …
```

chore: add mona lisa for missing chain logo

---

packages/react-app-revamp/components/_pages/ProposalContent/index.tsx

This is only a small increase in the size of `line-clamp` for desktop; we won't be using `line-clamp` in the near future because we will be returning to the proposal's content truncation. This is just a small enhancement while we are here.

enhancement: increase line clamp in proposal preview

---

packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx

Closes #1274 
Issue was that input file reference wasn't cleared after user uploads an image in submission.

bugfix: reset file input after image upload in editor

---

packages/react-app-revamp/components/UI/DialogModalV3/index.tsx

On mobile devices, I've noticed there is a small padding at the top and bottom, so the submission does not display full-screen.

bugfix: remove padding in dialog v3 on mobile

---

packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
packages/react-app-revamp/helpers/csvTypes.ts
packages/react-app-revamp/workers/parseSubmissionCsv.ts
packages/react-app-revamp/workers/parseVotingCsv.ts

I tried to trigger behaviour in #1209, but i was unable to do it in any way. I believe we should close it for now.
First off, you can only apply for the waitlist at this time; you are unable to download Arc for Windows.
Secondly, i took the user address that they gave in the issue as the one that went on to create the contest, therefore i extracted the CSV file from that contest that contained 62k addresses. While i was there, i discovered that even though headers are not allowed, we do not raise a typical error if they are included, but rather we show it in the preview ( we should raise typical error in case of headers imo ) 
Therefore, i went ahead and added catch for the unexpected headers when CSV is being parsed.

enhancement: add unexpected headers error in csv parse

---

packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
packages/react-app-revamp/hooks/useContestInfo/index.tsx
packages/react-app-revamp/hooks/useTokenDetails/index.ts

I noticed that there is an infinite loading skeleton for the [Demo hack by DAO](https://jokerace.xyz/contest/optimism/0x897B3F3aa54A5a62FaC7BAb0Ac41DF26b6546145) contest in the list of contests for the submission requirements.
It looks like we were passing chain from `votingRequirements` rather than `submissionRequirements` in the list of contests.

bugfix: use chain from submission requirements in contests list

---

packages/forge/package.json
packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.4.22.refactorDistributionFunc.sol/flattenedContest.sol
packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/flattenedContest.sol
packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.4.22.refactorDistributionFunc.sol/flattenedRewardsModule.sol
packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/flattenedRewardsModule.sol

flattened files are what you need to verify contracts, so to make it easy for anyone to do, we should just provide them like we do the bytecodes and abis I think. just added logic to `yarn smartcheck` to do it programmatically, so not much extra development effort added at all for a ton of benefit in terms of making it straightforward for people to verify contracts themselves.

chore: add flattened files to flow

---

packages/react-app-revamp/hooks/useTokenDetails/index.ts

I've noticed that there isn't symbol for the voting requirement NFT on [this](https://www.jokerace.io/contest/base/0x594663fea4763c5d92f0ac298897f99860f60e29) contest
You can check it by going to the params tab, it is returning an empty string for the symbol, therefore, if symbol is empty we will try to retrieve name for that token.

bugfix: use name or symbol for token details in params tab

---

packages/react-app-revamp/package.json
yarn.lock

saw that `yarn install` time has gotten up there on Vercel (anywhere from 120-140 seconds), and so read that hard resetting the `yarn.lock` file by deleting it and running `yarn install` can help, and it looks like it has (bringing it down to 85 seconds), but now it's getting it to not break.
edit: done! just needed to update some dependency versions, namely `@babel/preset-env` and `@types/react`.

chore: speed up builds with hard yarn.lock reset

---

packages/react-app-revamp/hooks/useDeployContest/index.ts

We need to normalize empty contact details to empty string instead of undefined on deployment. This ensures consistency and prevents undefined values when contact details are not provided ( they are optional )

bugfix: add check for contact details in deploy contest fn

---

packages/react-app-revamp/config/wagmi/index.ts
packages/react-app-revamp/pages/_app.tsx
packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
packages/react-app-revamp/pages/contest/new/index.tsx
packages/react-app-revamp/pages/contests/index.tsx
packages/react-app-revamp/pages/contests/live/index.tsx
packages/react-app-revamp/pages/contests/past/index.tsx
packages/react-app-revamp/pages/contests/upcoming/index.tsx
packages/react-app-revamp/pages/index.tsx
packages/react-app-revamp/pages/user/[address]/comments/index.tsx
packages/react-app-revamp/pages/user/[address]/index.tsx
packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
packages/react-app-revamp/pages/user/[address]/votes/index.tsx
packages/react-app-revamp/providers/index.tsx

Closes #1441
Ok so this required a bit more of a codebase changes than i thought it would be.
In order to hydrate cookie for wagmi, we need to call `getServerSideProps` on each page and pass cookie for `cookieStorage` which is being initialized in the `app.tsx`, also, this means that nothing is going to be slower on our side, i also removed some redundant code which is good! 
Also, when i find some free time, i'll update wagmi docs and create an example of how to hydrate cookie for nextjs page router https://wagmi.sh/react/guides/ssr#next-js-pages-directory
So all after all, walletconnect and coinbase wallet are back in our app.

chore: hydrate cookie for wagmi ssr

---

packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/pages/_app.tsx
packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
packages/react-app-revamp/pages/contest/new/index.tsx
packages/react-app-revamp/pages/contests/index.tsx
packages/react-app-revamp/pages/contests/live/index.tsx
packages/react-app-revamp/pages/contests/past/index.tsx
packages/react-app-revamp/pages/contests/upcoming/index.tsx
packages/react-app-revamp/pages/index.tsx
packages/react-app-revamp/pages/user/[address]/comments/index.tsx
packages/react-app-revamp/pages/user/[address]/index.tsx
packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
packages/react-app-revamp/pages/user/[address]/votes/index.tsx

I have noticed that the prop `refetch` in `Link` component isn't being utilized when `getServerSideProps` is used within the page.
We are using now `getInitialProps` in the `_app.tsx` and that way we removed every `getServerSideProps` in each page and instead we are using `getStaticProps` which we used before. While this is a legacy API, it is better for us to use it now until we can transform app from page router to app router.
See difference by clicking on submission in contest page
From this PR - https://jokerace-edlhtp4sr-jokerace.vercel.app/contest/arbitrumone/0x1d472EeAbad83268D72A4a90d3F83e70F30EBbbF
In prod - https://www.jokerace.io/contest/optimism/0x4098e85bb0261d66f3295c4e3109d35f755d3f78
**LONG TERM SOLUTION**
Long term solution for us would be to switch from nextjs page …

chore: use initialProps in app rather than server side prop on each page

---

packages/react-app-revamp/config/wagmi/server.ts

Note: I'll create a `chain.ts` file soon so we can just export all chains from there and import in both client-side and server-side wagmi config

chore: add missing chains

---

packages/react-app-revamp/components/ChargeLayout/components/Vote/index.tsx

It looks too long when we say "charge for each vote" and this PR is reverting it to "charge per vote"

chore: fix language in voting widget

---

packages/react-app-revamp/app/api/[[...routes]]/route.tsx
packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
packages/react-app-revamp/hooks/useProfileData/index.ts
packages/react-app-revamp/lib/frames/submission/index.ts
packages/react-app-revamp/lib/frames/utils.ts
packages/react-app-revamp/lib/frames/voting/index.ts

Closes #1562 
We are using eth -> lens -> address order both for user profiles in our app and for frames, additionally, user profile performance should be much better ( caching is included now ) due to usage of `useQuery`

chore: apply eth -> lens -> address order for user profile

---

packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
packages/react-app-revamp/workers/parseVotingCsv.ts

Implementing a fix which is causing a BsOD in the voting tab in create flow, specifically in the upload csv section, when user is prompted with the invalid entries modal and tries to edit allowlist.

bugfix: fix error in voting invalid entries modal

---

packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx

We did not specify a `creatorSplitDestination` for every contest created before version `4.29`, so we should pass `contestAuthor` to the earnings component to show where creator earnings are going.

bugfix: add contest author for earnings in params tab

---

packages/forge/test/Contest.t.sol
packages/forge/test/RewardsModule.t.sol

forgot to update test pragmas when we standardized all contracts to `0.8.19` so doing that now.

chore: update test solidity version

---

packages/forge/package.json
packages/forge/test/Contest.t.sol
packages/forge/test/RewardsModule.t.sol

`forge flatten` no longer includes command line compilation information in its file output so we can remove the accommodation we made for that behavior in `forge/package.json` in https://github.com/jk-labs-inc/jokerace/pull/1420/commits/343fe4b696e3dbad296304d705a486d553c8e2f4.

chore: rm smartcheck extra line removal

---

packages/forge/package.json

just reverting the removal of the `tail` command, not the updates to `0.8.19` for `.sol` files. the newest foundryup just changed flatten again for some reason.

chore: revert #1664 and change to +3 with latest foundryup

---

packages/react-app-revamp/config/wagmi/custom-chains/sei.ts

closes #1738 - we were using the rpc endpoint for the devnet instead of mainnet

chore: update sei rpc to mainnet

---

renovate.json

https://docs.renovatebot.com/key-concepts/automerge/#automerge-non-major-updates
if the checks clear on patch and minor updates I think we're usually in the clear to merge so might as well automerge - we're going to have to manually patch into `main` either way so will always have a point where we check before it gets to prod.

chore: add minor and patch automerge

---

packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/index.tsx

Here is a screenshot of the enhancement because, for some reason, the tool i'm using won't let me compile .gif files smaller than 10MB. 
We have included a toggle so that users can choose whether to view or hide submissions.
EDIT: 
We have implemented a feature to save user preferences for hidden proposals in local storage. The data structure stores an array of proposal ids for each contest id. This allows users to have different hidden proposals for different contests.
Key points:
1. User preferences persist through page reloads.
2. Preferences reset when the user closes the tab or window.

enhancement: add show / hide toggle for submissions

---

packages/react-app-revamp/package.json
yarn.lock

[`@types/react-datepicker`](https://www.npmjs.com/package/@types/react-datepicker) has been deprecated, so removing.

chore: rm deprecated dependency

---

.husky/post-checkout

was getting the below so just removing the offending line, the yarn install on `git checkout`/`git switch` still works.

chore: delete breaking husky line

---

packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx

I've noticed that, instead of retrieving the balance of the contest chain when the contest is open to anyone, we are retrieving the balance of the connected chain for the card that displays the users native token balance and their corresponding votes. 
The previous logic was correct and in place, however when comparing the chain names, we must `lowerCase` them.

bugfix: lowercase chain name when fetching votes balance

---

packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx

When we check to see if the chain is included in the list of supported chains so that anyone can vote, we come across some weird conditionals in the `useEffect` in the confirm step of the confirm flow.
Therefore, in this PR we improved it to use `useCallback` and disable the button until we have details from the db.

bugfix: improve chain support redirect in create flow

---

packages/react-app-revamp/components/TokenSearchModal/components/TokenList/components/Token/index.tsx

Some token images in the search modal fail to load due to invalid source URLs (404 errors), resulting in broken images. 
This PR implements a fallback mechanism to ensure a default image is displayed when the original source fails to load, even if alchemy returns a seemingly valid URL. This addresses cases where the provided URL is actually invalid or inaccessible.

bugfix: add fallback for broken token images

---

renovate.json

the build keeps hanging for like 45 minutes which we just can't have with the limits of Vercel, so ignoring those updates for now.

chore: ignore react-native updates for now

---

packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/index.tsx

This PR moves the resize button for proposal images from within the image component to the proposal header area. This change addresses few UX issues and improves overall user interaction.
1. **Improved click accuracy**: Previously, the resize button was part of the image area, which is also a link to the proposal. This created a conflict where users might accidentally trigger the link when trying to resize the image. Moving the button out of the image eliminates this issue ( user still couldn't open it by clicking a resize button, it is just that behaviour is a bit messy ) 
2. **Reduced accidental interactions**: Even with `preventDefault()`, clicking the resize button within the image area could cause the loading bar to appear, giving a false impression of navigation. The new placement …

enhancement: move resize button out of image

---

packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/helpers/isContentTweet.ts

I have noticed that for [this](https://www.jokerace.io/contest/base/0xbf6b7c06e23a07b857d47d67fcae0dcd739d1a03) contest, some of the proposals do not render tweets ( check the first place proposal ) in the proposal preview. 
This is because of the limitations we had in the previous model for the proposal preview, since we no longer need those limitations, by removing it, we are always rendering the tweets if the proposal contains one.

bugfix: remove character length for tweets in proposal preview

---

packages/react-app-revamp/components/_pages/ProposalContent/index.tsx

During a recent refactor for image resizing, i mistakenly removed crucial code responsible for managing user preferences regarding proposal visibility. This PR restores the `toggleContentVisibility` function and reinstates proper local storage management for hidden proposals.

chore: restore proposal content visibility toggle and local storage management

---

packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
packages/react-app-revamp/helpers/isContentTweet.ts

Closes #2297 
Sometimes tweets come as `p` paragraph element rather than as `a` anchor element, not sure if this is due to user pasting incorrectly or our markdown editor making a mistake.
However, we should check if the paragraph contains full link for the tweet and render it in that case.

bugfix: tweets not rendering when they are paragraph element

---

packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx

I am not sure if this action is allowed on the contract side, can we use `setCreatorSplitDestination` function if percentage to creator is 0? 
This PR will not prevent it to happen on the front ( as long percentage to creator is 0, we do not allow to edit earnings or to set it during the rewards creation )

bugfix: hide earnings edit if percentage to creator is 0

---

packages/forge/package.json

every once in a while the foundry flatten command flipflops between including extra lines at the top or not and now it's not.

chore: update flattening script

---

packages/react-app-revamp/components/UI/Slider/index.tsx
packages/react-app-revamp/components/Voting/index.tsx

Closes #2232 
Let me explain why some of these issues aren't possible on desktop and mobile.
1. the purple cursor doesn't automatically blink in the voting field unless you tap it ( on mobile )
The issue with this one, is that you can't auto focus input on mobile due to various mobile restrictions with web app (both apple and android), the problematic part is that when input is focused on mobile, keyboard is open and therefore window dimensions are resized. Therefore, on load, you can't auto focus an input because mobile explorers have to calculate those dimensions in the background, and it can be done only manually (by clicking on the input), i have done lot of research on this area but in case i missed something or you find in some web app on mobile this behaviour, please let me know! …

enhancement: improve voting slider on mobile

---

.github/workflows/forge_tests.yml
.github/workflows/nextjs_build.yml

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-using-concurrency-and-the-default-behavior
tldr: this setting makes it so that a given workflow will only be scheduled concurrently with another trigger of the same workflow on the same branch a maximum of one time and that the already running workflow will finish, any workflow triggers between the current running workflow and the latest triggered workflow will be canceled.
tldrtldr: if you push 6 times to a branch before the workflow triggered by the first push finishes, only the first and sixth triggers will run, the ones in between those will be canceled. this will save us a lot of redundant build time.

chore: group actions on branch

---

packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
packages/react-app-revamp/hooks/useContestInfo/index.tsx

In this PR we replaced all instances with `entering closed` with `entries closed`

wording: update submission language for contests

---

packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/index.tsx

Closes #2455 
Issue here was that when we transform the markdown, we check if the proposal is tweet, but the issue is when we check if paragraph contains the tweet. This transform check where if tweet is contained somewhere in the paragraph can introduce buggy behaviour in the markdown.
However, i think that we need to have strict rules here in order to maintain markdown clean and that is that tweet can only be in the anchor link, which makes most sense because only then it contains link to the tweet in `href`, in the future we can have an option to add tweet directly from options ( like we have for images, for heading etc .. )

bugfix: fix tweet rendering issue

---

packages/react-app-revamp/components/Voting/index.tsx
packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx

Closes #2485
I have noticed that there is a confusion between users when they do not have enough balance for anyone-can-vote contests in the entry page as currently we show them a message which tells them that they do not qualify, while this isn't a bug we need to have a clearer message.
We forgot to accommodate this language for anyone-can-vote contests, so i just added a simple message that we already have on the contest page, such as `add {chainCurrency} to {chain} to get votes` if user does not have enough balance to vote on the entry page.

enhancement: add different language for anyone can vote in voting widget

---

packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/index.tsx

It looks like position of the entry collapse button which was next to the entry author name was confusing to some users, so for better clarity and positioning we are moving it to the right side.

enhancement: move entry collapse button to the right

---

packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
packages/react-app-revamp/hooks/useDeployContest/index.ts

Closes #2521
We have `MAX_SUBMISSIONS_LIMIT` and `DEFAULT_SUBMISSIONS` and we forgot to update `MAX_SUBMISSIONS_LIMIT` const to be 10,000. 
Reason we have those two is that previously we wanted to default some number to the user and max was different than that, let's still keep it this way in case we change numbers in the future if that sounds good!

bugfix: set max submissions per contest const to be 10,000

---

renovate.json

have renovate run 11pm-6am UTC so that it doesn't interfere with development flow.

chore: set up renovate scheduling

---

packages/react-app-revamp/hooks/useContest/index.ts

I have noticed some weird behaviour in our app when you switch between contest that has ended and submission / voting was allowlisted and contest in which you are allowed to play.
One example is, i was looking at climate contest ( submission was allowlisted there and i wasn't allowlisted ) and i switched to landing page and opened applympics contest. It said that i wasn't allowlisted to enter while it is anyone-can-enter contest.
After some digging, i found out that `contestStatus` isn't refreshed in the `hooks\useContest\index.ts` as it is being called after that, and in there we had a check that if `contestStatus = voting closed`, do not process user qualifications. While this check could be useful to not call those qualifications if contest has ended, by simply removing it now it won't …

bugfix: rm contest status check in user qualifications

---

packages/react-app-revamp/hooks/useCastVotes/index.ts
packages/react-app-revamp/utils/error.ts

Closes #2618
In this PR, we added following: 
- Implement `simulateContract` to validate transactions before execution ( for castVote ) 
- Update error handling utility to catch specific insufficient funds errors from simulation (added a new check for error messages containing "insufficient funds for gas * price + value", as these simulation errors often lack standard error codes and require message compare)

bugfix: add contract simulation and enhance insufficient funds error detection

---

packages/react-app-revamp/utils/error.ts

I have noticed that if you reject a transaction, error is thrown via toast, while it doesn't effect anything, we shouldn't treat this as an error. 
This is also due to lack of standard error codes so we should add checks for "user rejected" and "user denied" phrases in `didUserReject` fn

chore: enhance didUserReject function to catch more user rejection scenarios

---

packages/react-app-revamp/lib/permissioning/index.ts

Closes #2755 
Closes #2746
Closes #2743
We were using a quicknode url instead of alchemy for fetching NFT holders data, so in this PR, we are correctly assigning a alchemy url per chain.

bugfix: fix alchemy url for nft holders

---

packages/react-app-revamp/hooks/useContest/index.ts

Closes #2679
During the small refactor, we moved `sortEnabled` check in the monetization check, therefore for all chains that do not have monetization set, `sortEnabled` would be false and therefore message like above in the issue would appear.

bugfix: move sort enabled check out of monetization check

---

packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
packages/react-app-revamp/lib/proposal/index.ts

Closes #2808
We had previously a check if the entry is deleted, however, it looks like this one is a tweet, therefore it didn't catch it based on content.

bugfix: catch correctly deleted entries

---

packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx

Interweave, our library for rendering markdown does not break link into the next row, so we have to use `overflow-hidden` in order to prevent link from going outside of the container.

bugfix: add overflow hidden to entry container in leaderboards

---

packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx

Closes #2848 
I tested it by switching between hidden and false, so the issue wasn't with the functioning; rather, it was with appearance.
The progress bar is only in charge of page switching within our application; it is not in charge of action states. In cases where there are nested clicks within link components, like this one, where the link has a toggle feature for the contest itself, we have to stop propagation to prevent the progress bar from showing. In this case, the user thought that the progress bar itself was a toggle indicator, which was an issue on our side for displaying it.

bugfix: unable to toggle contest visibility in profile

---

packages/react-app-revamp/hooks/useEmailSignup/index.tsx
packages/react-app-revamp/supabase_schemas/email_signups.sql

Closes #2946 
We are storing it as a `timestampz` type in the supabase, which means that we include timezone in it. 
TODO:

feat: add timestamp in subscribe fn

---

packages/react-app-revamp/components/_pages/Contest/components/Prompt/SubmissionQualifierMessage/index.tsx

wording: update allowlist wording to present tense

---

packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx

After our recent addition to the contest prompt ( image URL ) i have noticed that the metadata for contest link is broken, title of the contest is there but description is missing ( this is only for the contests that were created after image URL addition ) 
This is because we changed the way we create this string during the deployment after we added image URL, i was thinking of how can we make these additions to the prompt easier for us in the codebase and now we use `URLSearchParams` now as it is easier to add / remove on top of the prompt string and later to extract from it. 
This PR should fix the issue with the metadata when sharing a link, i'll watch closely once this is shipped!

bugfix: fix metadata for contest link

---

packages/react-app-revamp/components/_pages/Contest/Rewards/components/TotalRewardsInfo/index.tsx
packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/Mobile/index.tsx
packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
packages/react-app-revamp/helpers/formatBalance.ts
packages/react-app-revamp/tailwind.config.js

Due to our conversation in TG, we are implementing a better and shorter transition for numbers in rewards pool, additionally, for any value above 1000, we are formatting it.

enhancement: add better transition for numbers in rewards pool

---

packages/react-app-revamp/config/s3/index.ts

closes #3228 
caused by #3223, solution from Cloudflare forum discussion [here](https://community.cloudflare.com/t/aws-sdk-client-s3-v3-729-0-breaks-uploadpart-and-putobject-r2-s3-api-compatibility/758637/11)

bugfix: cors checksum aws update issue

---

packages/react-app-revamp/config/s3/index.ts

Based on the latest comment from cloudfare forum https://community.cloudflare.com/t/aws-sdk-client-s3-v3-729-0-breaks-uploadpart-and-putobject-r2-s3-api-compatibility/758637/13, looks like `responseChecksumValidation` config param is also needed in the s3 config.

chore: add s3 response checksum validation

---

packages/react-app-revamp/hooks/useCastVotes/index.ts
packages/react-app-revamp/hooks/useSubmitProposal/index.ts

Closes #3166
After i did some research, it could be that `Promise.all` could introduce duplicate behaviour here, so we replaced `Promise.all` with sequential await calls in order to try and prevent it. 
Let's make sure that analytics operations complete one at a time to avoid possible race conditions and duplicate entries.

bugfix: prevent duplicate analytics entries by sequential executions

---

packages/react-app-revamp/hooks/useComments/index.ts
packages/react-app-revamp/hooks/useProposal/index.ts
packages/react-app-revamp/hooks/useProposalVotes/index.ts

just lowering the number of concurrent calls we do per page for entries, comments, and voters to help minimize concurrent call surges and consequently/ideally the times we get rate-limited/run up against our Requests Per Second limit.

chore: lower concurrent calls

---

yarn.lock

is getting to where we have 3 of these warnings each build now so thought it was time to update. just ran the command it prompts and then made sure that the registry was pointing to `yarnpkg` instead of `npmjs`.

chore: rm browserlist warning

---

packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/custom-not-found.tsx
packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/index.tsx

Closes #3311 
We got a response from[ this ticket ](https://github.com/vercel/react-tweet/issues/188) and it looks like this specific tweet is flagged as NSFW, therefore users who aren't logged in, can't see the tweet. 
You can try opening a [tweet ](https://x.com/mmyselfvvanilla/status/1887932387738157104)in incognito mode and it won't be able to render, i found an error as well in the network tab 
I propose that in cases like this, we enrich our component and instead of saying "embedded tweet not found.." we give more info and also a CTA for user to open a tweet in a new window. Since API returns just 404 we do not know if either tweet is deleted or flagged as NSFW, therefore we have to give some generic message. 
Let me know what you think of this approach @divine-economy

bugfix: enrich tweet not found component

---

packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx

Closes #2555 
One potential reason for this could be that for entry mobile page, instead of using a modal for mobile (we need full-height anyways), we should use directly div that will overlay the content behind (contest page) , let's implement this and see if this behaviour from the tickets happens again in the future.

bugfix: fix entry alignment on mobile

---

packages/react-app-revamp/components/_pages/ListProposals/index.tsx
packages/react-app-revamp/components/_pages/ListProposals/skeleton.tsx

Closes #3465 
This is just a quick fix for the bug above. We should get rid of the `react-infinite-scroll-component` package as it is not maintained anymore and has lot of bugs, explained more in the dev channel.

bugfix: fix scroll threshold for entries

---

packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx

I have noticed that if you select a template which has `PerVote` charge settings enabled (anyone can play), and if you move backwards in that template and actually select a entry contest type which means `PerTransaction` charge settings will be enabled for voting, while in UI it does reflect that change, we still set `PerVote` when we deploy a contest.

bugfix: fix vote charge settings

---

packages/react-app-revamp/components/UI/ImageUpload/index.tsx

I noticed that we previously allowed image uploads up to 20MB, which is extreme for web and could cause performance issues. 
Large images could:
- Increase page load times and bandwidth usage
- Create poor UX during upload/download
- Cause memory issues on mobile devices
A 5MB limit is enough for high-quality images (even 4K images usually range from 2-4MB) while preventing these potential problems.

chore: reduce image file upload size

---

packages/react-app-revamp/hooks/useUser/index.ts

I noticed that when pay-per-vote is enabled on contests, `userVotesFormatted` sometimes ends up not being a whole number (in my case 4016.9999999999995). This PR adds `Math.floor` to ensure we always get a clean integer value.

chore: fix vote calculation precision with Math.floor

---

packages/react-app-revamp/hooks/useProposal/index.ts
packages/react-app-revamp/hooks/useProposal/utils.ts

There is a small bug that is currently in prod, if you go over [this contest](https://www.jokerace.io/contest/base/0xba9d6fa92b812b84f172fa77b7eeba73ed375516)  and click on any entry, ranks won't be included.
Issue is that i have i missed to update new logic in 2 places in our codebase, everything should be working correctly now!

bugfix: fix undefined BigInt conversion in entry votes

---

packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/utils/markdown.tsx

We should use `light` in the className for the tweets, as suggested [here](https://react-tweet.vercel.app/#toggling-theme-manually)
I thought if not passed, that `light` is set by default but it isn't, tweets look much better now with this selector
| before | after |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/5046e2d9-91ba-4f16-82b0-ad6008434023)  | ![image](https://github.com/user-attachments/assets/274c96d4-3f84-4744-8c9d-1f5633d99da5)   |

enhancement: use light class selector for tweets

---

packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx

I have noticed that for [this contest](https://www.jokerace.io/contest/polygon/0x69a42939b1db1455e7150b79794d0b392f2b26f9) scrollbar appears with the height of the actual contest description when it is expanded (but it isn't) and footer isn't fixed to the bottom.
Issue here was, when contest description is way too long, main container takes that height instead of keeping the height of non-expanded contest description, hence why scrollbar appears and why footer isn't fixed.
EDIT: I think this was a known issue before, someone noticed that for some contests footer isn't fixed, so it was this issue.
EDIT 2: Oh i think this was also the issue with some contests not loading entries at specific point on the site (you had to load way more in order for them to load, i added hotfix back then, but …

bugfix: fix collapsed description container height to prevent extra scrolling

---

packages/react-app-revamp/styles/globals.css

I have noticed that on [this contest](https://jokerace.io/contest/base/0x164a82dd414dfa53e5c8efe1e18db8cf7fd66d5b) dark background color is applied to the quoted tweet, while `light` class should override it, we should still remove it from the `global.css`

chore: rm background color on quoted tweet

---

packages/react-app-revamp/hooks/useDeployContest/index.ts

Closes #3538
I think the issue lays in `getEthersSigner`, where we are attempting to get `signer`, but due to stale connection, it errors out. 
Let's add try/catch in this iteration, and we can check with tavvi if she gets immediate error for this one (we would initialize error before the deployment screen appears with a message "Please try reconnecting your wallet.")

chore: add try/catch for signer during contest deployment

---

packages/react-app-revamp/components/SendFunds/index.tsx
packages/react-app-revamp/components/TokenSearchModal/ERC20/index.tsx
packages/react-app-revamp/components/TokenSearchModal/MultiStep/components/Form/index.tsx
packages/react-app-revamp/components/TokenSearchModal/MultiStep/index.tsx
packages/react-app-revamp/components/TokenSearchModal/NFT/index.tsx
packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
packages/react-app-revamp/components/TokenSearchModal/components/SearchInput/index.tsx
packages/react-app-revamp/components/TokenSearchModal/components/TokenList/components/Token/index.tsx
packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
packages/react-app-revamp/components/TokenSearchModal/index.tsx
packages/react-app-revamp/components/TokenSearchModal/types.ts
packages/react-app-revamp/components/UI/DialogModalV4/index.tsx
packages/react-app-revamp/components/UI/MobileWalletPortal/index.tsx
packages/react-app-revamp/components/UI/UserProfileDisplay/componentts/SendFundsButton/index.tsx
packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
packages/react-app-revamp/hooks/useSendToken/index.ts
packages/react-app-revamp/hooks/useTokenList/index.ts
packages/react-app-revamp/layouts/LayoutUser/index.tsx

Closes #3525
Let's make this serve as an MVP, current flow is:
1. When user visits their profile, send funds button appear.
2. When clicked on send funds button, token search modal would open (i'm including native token as first in the list of user's tokens since i guess most of the time they will send native token)
3. When clicked on token from the modal, they are brought to the second step of the form, where they can specify recipient address and amount they wish to send. Once submit is clicked, tx is initialized.
For now, sending only to these chains is supported, because we can only fetch for tokens on these chains
```
export const erc20ChainDropdownOptions: Option[] = [
{
value: "mainnet",
label: "ethereum",
},
{
value: "arbitrumone",
label: "arbitrum",
},
{
value: "avalanche", …
```

feat: send funds button on user profile

---

packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx

I have noticed that if there are no votes in the entry page header (empty space) close button on the right side goes down and messes up with the navigation actions. 
This is because we aren't preserving space to align with the close button when entry has no votes.

bugfix: fix close button style on entry page on desktop

---

packages/react-app-revamp/components/_pages/Submission/index.tsx

I have noticed that sometimes there could be a small delay when you are trying to close entry page modal, we should use `prefetch` along with `router` here as explained [here](https://nextjs.org/docs/pages/api-reference/functions/use-router#routerprefetch)

chore: prefetch close entry action on entry page

---

packages/react-app-revamp/app/contests/search.tsx
packages/react-app-revamp/app/layout.tsx
packages/react-app-revamp/app/not-found.tsx
packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
packages/react-app-revamp/components/Sort/index.tsx
packages/react-app-revamp/components/UI/Link/index.tsx
packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
packages/react-app-revamp/components/_pages/Submission/index.tsx
packages/react-app-revamp/package.json
yarn.lock

I'm noticing some weird delay again when closing entry page, or when leaving browser open and coming back to it and trying to navigate between pages. 
While i really like `next-view-transition` lib i think it's not necessary as of right now, when we upgrade to nextjs 15 we will have this native support that we can enable, so we will get there eventually. Keep in mind, that pages will still be instantly navigated with our `prefetch` mechanic, this will just reduce that smooth effect of navigation (by upgrading to nextjs 15 we will have this as well)

chore: rm view transition lib

---

packages/react-app-revamp/components/Onramp/providers/coinbase/utils.ts

I have noticed that if you try to add funds and onramp with arbitrum, we currently show disabled status for that chain, while coinbase does support it.
Issue was, we are configuring `arbitrum` as `arbitrumone`, and we should map and configure it to check our internal config for `arbitrumone` and pass it as `arbitrum` to the onramp URL.

bugfix: fix arbitrum onramp

---

packages/react-app-revamp/package.json
yarn.lock

We should remove `lens-protocol-client` as it isn't used anywhere in the codebase

chore: rm lens protocol client

---

packages/react-app-revamp/package.json
yarn.lock

We should remove `valibot` as we do not use that library anywhere in the codebase.

chore: rm valibot

---

renovate.json

draft until we have the current backlog solidly cleared so we don't get hit with a huge flood of PRs all at once.
we still won't allow major update PRs to auto-merge, but we will allow them to be created for visibility.

chore: allow major update PRs to be made without approval

---

renovate.json

bringing back `react-native` dependency updates after pausing them in #2107 to see if working correctly now

chore: bring back react native dep

---

packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/TweetLayout/index.tsx
packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/index.tsx

Closes #3778
While we had internal validation check for tweet, in case it is invalid, we didn't set it to empty string in order to activate validation in the parent components.

bugfix: prevent user from submitting invalid tweet entry

---

packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
packages/react-app-revamp/components/_pages/FeaturedContests/index.tsx
packages/react-app-revamp/components/_pages/Landing/components/index.tsx
packages/react-app-revamp/hooks/useTotalVotes/index.ts
packages/react-app-revamp/lib/contests/constants/index.ts
packages/react-app-revamp/lib/contests/contracts.ts
packages/react-app-revamp/lib/contests/index.ts
packages/react-app-revamp/lib/contests/types.ts
packages/react-app-revamp/lib/contests/utils/streamItems.ts
packages/react-app-revamp/lib/user/index.tsx

Closes #2820
I'm just doing some refactor for contests calls, mostly wanna optimize and set a ground for using a parallel technique where we load all contests one-by-one, this will first take effect for the featured contests (landing page), will write more technical info here soon.
In this PR we are introducing 2 functions that are responsible for streaming items one-by-one (`streamProcessItems` and `streamPromiseResults`) and it's reusable so we can use it across all other contests calls (search, live contests, past, upcoming) or even in some non-db calls by calling  `streamPromiseResults` but in this PR i would only implement it for featured contests to see how it behaves in prod and move on from there. 
Main idea is, whenever we have a batch of items that we want to load, we should …

enhancement: refactor contests calls

---

packages/react-app-revamp/hooks/useClaimRewards/index.ts

I just noticed a small bug, if your wallet is connected to a different chain than a contest chain and if you try to claim rewards, we throw an error. I just added our standard technique where we switch to a contest chain with `switchChain` fn from wagmi.

bugfix: switch chain in claim rewards

---

packages/react-app-revamp/components/_pages/Contest/Parameters/components/Rewards/components/Table/index.tsx

We should use `data` as returned from the call instead of `index` when rendering shares for rewards table in rules tab of the contest.

bugfix: use data instead of index in rewards table in rules tab

---

packages/react-app-revamp/hooks/useDeleteProposal/index.tsx

There was a critical bug for comparing versions for entrants delete functionality, instead of using `compareVersions` package we used to compare if current version match exact `ENTRANT_CAN_DELETE_VERSION`, which resulted in entrants not seeing delete button.

bugfix: fix compare versions for entrants delete functionality

---

packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/components/Timer/index.tsx
packages/react-app-revamp/helpers/exponentialMultiplier.ts
packages/react-app-revamp/hooks/useCurrentPricePercentageIncrease/index.ts

Closes #4124 
If the percentage is below `PERCENTAGE_INCREASE_THRESHOLD` which current value is `0.1` we track it and instead of displaying percentage in the UI, we just use an up arrow.

bugfix: fix percentage issue in vote price when below threshold

---

.github/workflows/nextjs_docker.yml
Dockerfile
packages/react-app-revamp/next.config.js

DigitalOcean has started being weird with running out of memory when building the site, and also builds have gotten really long with them, like up to 16 minutes now. So moving to building our own image and then just having DigitalOcean use that will give us a lot more control over the process, isolate DigitalOcean's role to just hosting and serving the site, and also speed up deployment time.

feat: add docker build and push

---

packages/react-app-revamp/components/UI/TypewriterCycler/index.tsx
packages/react-app-revamp/components/_pages/Landing/components/index.tsx
packages/react-app-revamp/package.json
yarn.lock

In the latest motion updates, they introduced a `Typewriter` component that creates typewriter animations. With that update, we no longer need `react-type-animation` lib and we can remove it without adding any new one.

chore: replace react-type-animation lib with motion

---

packages/react-app-revamp/hooks/useProfileData/index.ts

I have noticed that same cluster name appears on voters list multiple times, it looks like clusters are now returning it's name in a response so we do not need `normalizeClusterName` helper anymore, issue is that we were splitting text by `/` and that was returning back just `campnetwork/` instead of `campnetwork/median`

chore: use new clusters api

---

packages/forge/foundry.toml

in foundryup's new stable version, v1.3.2, they default opt people in to linting on builds, which made our `yarn smartcheck` output unreadable because the linting logs were appended, so disabling for now.

chore: turn off linting on build with new foundry update
