jk-labs-inc/jokerace

- packages/react-app-revamp/layouts/LayoutViewContest/VotingToken/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/export-data/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/proposal/[proposal].tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/rules/index.tsx
#19 
- Change wording to put emphasis on 'Remaining votes' when votes are open and 'Used votes' when votes are closed
#19
> Bugfix 19/total votes displayed value

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/StepIndicator/index.tsx
- packages/react-app-revamp/helpers/getContestContractVersion.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
- packages/react-app-revamp/layouts/LayoutContests/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/package.json
- yarn.lock
* feat: handle errors graciously with react-error-boundary
Co-authored-by: Sean McCaffery <sean.mccaffery9@gmail.com>
> feat: handle errors graciously with react-error-boundary (#63)

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/StepIndicator/index.tsx
- packages/react-app-revamp/helpers/getContestContractVersion.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
- packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
> bugfix: await loading before rendering proposals

- packages/react-app-revamp/components/FormRadioOption/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/VotingToken/index.tsx
* bugfix: remove voting token address as default value of submission token address
* bugfix: align radio inputs on baseline
> merge #79 and #80 into main

- README.md
Make jokedao lowercase in the README.
> docs: make jokedao lowercase in the README

- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContestEvents/index.ts
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
- packages/react-app-revamp/hooks/useProposalVotes/store.ts
Note: You can start reviewing this PR, but please take into account the bug fixed in #89 appears in this PR  (#89 bugfix should fix the following bug: `when a user is on a different network/no network and checks a proposal page, a flashing error appears then the proposal data and its votes load properly`). 
* Feature: add pagination to votes list in proposal details page (votes are now displayed 5 by 5)
- `hooks/useProposalVotes/index`: use the same pagination logic for the votes as in `useContest`;
- `fetchProposalVotes()`: fetch the list of address that casted votes for this proposal + setup pagination + order the votes list to have current user's votes first (if their wallet is connected and if they casted votes for this proposal)
- `fetchVotesPage()` : fetch page of votes for a given …
> feat: add pagination to votes list in  proposal page

- packages/react-app-revamp/components/Button/styles.ts
- packages/react-app-revamp/components/_pages/ButtonDownloadContestDataAsCSV/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step1/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/Form.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step4/TextInstructions.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useExportContestDataToCSV/store.ts
- packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
- packages/react-app-revamp/styles/globals.css
- packages/react-app-revamp/tailwind.config.js
* Bugfix: fix download CSV file failing after loading 13 proposals
* Bugfix: fix missing votes data in CSV file (#72)
* Bugfix: include against votes in original proposal sort for pagination
* Bugfix: change CTA style in create contest/tokens wizard form steps
* Feat: Customize tailwindcss/typography to get bigger font size in rich text
> sprint ending 9/20/22

- packages/react-app-revamp/components/Button/styles.ts
- packages/react-app-revamp/components/TipTapEditor/index.tsx
- packages/react-app-revamp/components/TipTapEditorControls/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/layouts/LayoutBase/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Timeline/Countdown/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/VotingToken/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/pages/contest/new/index.tsx
- packages/react-app-revamp/styles/globals.css
* feat: add FAQ and request feature links to footer (#101)
* feat: new UI for proposals list and proposals page (#102)
* feat: new ui list proposals
* feat: change label from 'read more' to 'read full proposal
* feat: increase container width, change grid in contest layout
* feat: add additional instruction (must end with a valid image extension like .png, .jpeg, .gif ...) in window.prompt of tiptap image extension
* feat: add indicator on sidebar (desktop) and fixed top bar (mobile) when submissions are closed
* bugfix: fix opacity issue on submit proposals button on mobile when button is disabled
* bugfix: enable "Timeline" button on mobile even when user is browsing the contest on the wrong chain
>  sprint ending 9/27/22

- README.md
> docs: add example link to bytecode deployment

- README.md
- packages/react-app-revamp/codegen.yaml
- packages/react-app-revamp/components/EtheuremAddress/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/config/urql/index.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/graphql/common.graphql
- packages/react-app-revamp/graphql/generated.ts
- packages/react-app-revamp/graphql/get-default-profile.graphql
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/store.ts
- packages/react-app-revamp/hooks/useContestEvents/index.ts
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Timeline/Countdown/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/package.json
- packages/react-app-revamp/pages/contest/[chain]/[address]/proposal/[proposal].tsx
- packages/react-app-revamp/services/lens/getDefaultProfile.ts
- packages/react-app-revamp/tsconfig.json
- yarn.lock
sprint ending 10/18/22
docs: add example link to bytecode deployment
bugfix: only live update votes in the last hour of the voting period of a contest
bugfix: remove all listeners after the voting period is over
bugfix: get rid of providers bc should be able to do without being logged in
feat: display lens profiles in proposals and votes
> merge sprint ending 10/18/22

- packages/react-app-revamp/hooks/useContestEvents/index.ts
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
sprint ending 10/25/22
* bugfix: remove vote event cutoff race condition
> merge sprint ending 10/25/22

- LICENSE
- packages/react-app-revamp/components/_pages/RewardsWinner/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/rewards/index.tsx
- bugfix: allow and render decimals for share and payout amounts (#125)
- update LICENSE to jk labs (#126)
> merge sprint ending 12/13/22

- packages/react-app-revamp/components/DialogModal/index.tsx
- packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
- packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
- packages/react-app-revamp/components/_pages/DialogFundRewardsModule/schema.ts
- packages/react-app-revamp/components/_pages/RewardsWinner/Reward.tsx
- packages/react-app-revamp/components/_pages/RewardsWinner/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/Form.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
- packages/react-app-revamp/helpers/ordinalize.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useRewardsModule/index.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/rewards/index.tsx
> Feat/apply new UI reco to rewards flow

- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/index.tsx
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/schema.ts
- packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
- feat: Replace token amount rewards  by % amount rewards
> feat: display ranking rewards as percentage

- .gitignore
- package.json
- turbo.json
- yarn.lock
Removed unused workspaces and added turbo to the repo with `turbo.json` and by adding it as a dev dependency. Updated Vercel's build command to be `turbo build` as well.
> chore: add turbo

- packages/react-app-revamp/config/react-toastify/animations/FadeInOut.tsx/index.ts
- packages/react-app-revamp/pages/_app.tsx
- packages/react-app-revamp/styles/globals.css
Closes https://github.com/JokeDAO/JokeDaoV2Dev/issues/212
Toasts now have our custom fadeInOut animation and a little box shadow. I chose to add shadows because I like the way they outline the toasts. 
I'm unsure if I should speed up the fading in and out, but I really like how it does so gently. Ofc, it could just be me :)
Let me know if we can improve this!
https://user-images.githubusercontent.com/18723426/227201822-9fea6415-025a-478a-87a6-ddba21a62844.mov
> enhancement: add fadeInOut animation and shadows to toasts

- .github/ISSUE_TEMPLATE/chain_request.md
Clarify process to request a chain integration.
> chore: update chain request template w forking

- .github/ISSUE_TEMPLATE/chain_request.md
- packages/react-app-revamp/components/Share/index.tsx
- packages/react-app-revamp/helpers/share.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> patch PR 1 of sprint ending 4/4/23

- packages/react-app-revamp/config/wagmi/custom-chains/avax.ts
- packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
- packages/react-app-revamp/config/wagmi/index.ts
> feat: add avalanche c-chain

- packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 2 of sprint ending 4/4/23

- packages/hardhat/package.json
Weird legacy code that started causing errors so removing.
> chore: remove postdeploy

- README.md
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/helpers/submissionCaching.ts
> merge sprint ending 5/9/23

- packages/react-app-revamp/components/Clock/index.tsx
- packages/react-app-revamp/components/Explainer/index.tsx
- packages/react-app-revamp/components/Header/LandingHeader/index.tsx
- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/hooks/useContestInfo/index.tsx
- packages/react-app-revamp/lib/contests/index.ts
- packages/react-app-revamp/pages/index.tsx
Closes https://github.com/jk-labs-inc/jokerace/issues/221 - It is already closed but we should re-open it because of updates to design or create a new issue.
List of stuff that needs to be done:
- page is big unless zoomed out
- ~~drop requirements for submissions based on gas~~
- ~~change spacing~~
- ~~mobile bug on contests when wallet is not connected~~
- header over the explainer for mobiles is done, set it to be 20px but not sure if it is me or it looks small compared to the number circles below, could be just me.
- ~~stage one to three takes up valuable real estate~~
- ~~punctuation issues on 1-4~~
- ~~same size for logo and circle and center voting / submissions open~~
> refactor: implement minor visual improvements on landing for both mobile & desktop

- packages/react-app-revamp/hooks/useContestEvents/index.ts
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
> patch PR 1 of sprint ending 5/30/23

- packages/react-app-revamp/pages/index.tsx
> merge sprint ending 5/30/23

- packages/react-app-revamp/lib/contests/index.ts
Currently, if we define a contest as featured in a DB it appears at the end of the list on the landing, reason for that it since we don't have ordering system for now.
Let's apply this fix to order them by closest date so new ones appear on top while closed will be at the end.
> refactor: update featured contests to order list by closest date

- packages/react-app-revamp/lib/contests/index.ts
> merge sprint ending 6/6/23

- packages/react-app-revamp/config/wagmi/custom-chains/zora.ts
- packages/react-app-revamp/config/wagmi/index.ts
Add the Zora chain announced [here](https://twitter.com/ourZORA/status/1671602236219355136?s=20).
> chain: add zora chain

- packages/forge/test/RewardsModule.t.sol
Add tests for the `release()` function when called for an ERC20 token.
> test: add ERC20 rewards tests

- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
- packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
- packages/react-app-revamp/helpers/parseVotingCsv.ts
Remove header requirement for CSVs. CSVs now only should have 2 columns of data, no headers or anything.
> bug: remove headers requirement from csv upload

- packages/react-app-revamp/components/_pages/Create/utils/csv.ts
> patch PR 2 of sprint ending 7/11/23

- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
> patch PR 3 for sprint ending 7/11/23

- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
- packages/react-app-revamp/components/_pages/Create/utils/csv.ts
> patch PR 4 of sprint ending 7/11/23

- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
> bug: connected address doesn't show in top voters

- packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Super small but I just think this looks better, what are your thoughts?
> chore: remove Contest from title

- README.md
- packages/react-app-revamp/README.md
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
- packages/react-app-revamp/helpers/parseVotingCsv.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
- #323 
- #324 
- #331 
- #332 
- #334 
- #336
> patch PR 5 of sprint ending 7/11/23

- packages/react-app-revamp/hooks/useContestEvents/index.ts
~~For now, i've just commented part of code that was throwing error as i'm still unsure why that else is needed in first place, since `args` should always come through vote cast event.~~
~~Everything works good for now, but let's keep it until i eventually modify these listeners.~~
> bug: fix error while casting votes

- packages/react-app-revamp/hooks/useContestEvents/index.ts
- packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useUser/index.ts
> patch PR 6 of week ending 7/11/23

- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
For some reason this got excluded from #324 by accident so just putting in here.
> chore: don't sort proposal voters

- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 7 of week ending 7/11/23

- packages/react-app-revamp/config/wagmi/custom-chains/lootChainMainnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/lootChainTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 9 of week ending 7/11/23

- packages/react-app-revamp/supabase_schemas/contest_participants_v3
- packages/react-app-revamp/supabase_schemas/contests_v3.sql
For posterity and version control!
> chore: add supabase schemas to repo

- packages/react-app-revamp/config/wagmi/custom-chains/nearAuroraMainnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/nearAuroraTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/supabase_schemas/contest_participants_v3
- packages/react-app-revamp/supabase_schemas/contests_v3.sql
> patch PR 10 of week ending 7/11/23

- packages/react-app-revamp/config/wagmi/custom-chains/gnosisMainnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/gnosisTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/lib/contests/index.ts
- packages/react-app-revamp/styles/globals.css
> patch PR 1 of week ending 7/18/23

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/helpers/editor.ts
- packages/react-app-revamp/tailwind.config.js
Issue was laying in setting overall styles for `br`, we do not use those styles anymore.
> bug: fix rich text editor on firefox

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/helpers/editor.ts
- packages/react-app-revamp/tailwind.config.js
> patch PR 3 of week ending 7/18/23

- TOS.md
- packages/react-app-revamp/components/Parameters/index.tsx
- packages/react-app-revamp/components/UI/ButtonV3/index.tsx
- packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/utils/validation.ts
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useUser/store.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/ProposalStatistics/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Countdown/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
- packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
> patch PR 5 of week ending 7/18/23

- packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
- packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
- packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
- packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
- packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/index.tsx
- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
- packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
- packages/react-app-revamp/helpers/tokens.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
- packages/react-app-revamp/hooks/useFundRewards/index.ts
- packages/react-app-revamp/hooks/useRewards/index.ts
- packages/react-app-revamp/hooks/useTokenBalance/index.tsx
- packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
- packages/react-app-revamp/lib/contests/index.ts
- packages/react-app-revamp/styles/globals.css
- packages/react-app-revamp/tailwind.config.js
> patch PR 6 of week ending 7/18/23

- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> patch PR 7 of week ending 7/17/23

- packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
- packages/react-app-revamp/helpers/parseVotingCsv.ts
Bump up the limit to 100k for allowlists.
> chore: up to 100k allowlists

- README.md
- packages/react-app-revamp/README.md
- packages/react-app-revamp/components/Share/index.tsx
- packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
- packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonMumbai.ts
- packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkMainnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
- packages/react-app-revamp/helpers/parseVotingCsv.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/store.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Tabs/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/lib/contests/index.ts
- #402 
- #403 
- #405 
- #406 
- #408
> merge sprint ending 7/18/23

- packages/react-app-revamp/config/wagmi/custom-chains/mantleMainnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/mantleTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 2 of week ending 7/25/23

- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableRow/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionDate/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Recipients/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/Prompt/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
- packages/react-app-revamp/styles/globals.css
> patch PR 3 of week ending 7/25/23

- packages/react-app-revamp/components/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
- packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
- packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
- packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
- packages/react-app-revamp/hooks/useFundRewards/index.ts
- packages/react-app-revamp/hooks/useRewards/index.ts
- packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
- packages/react-app-revamp/public/rewards/distributed-ellipse.svg
- packages/react-app-revamp/public/rewards/no-funds-distributed-ellipse.svg
- packages/react-app-revamp/styles/globals.css
> patch PR 4 of week ending 7/25/23

- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/helpers/formatNumber.ts
> patch PR 5 of week ending 7/25/23

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonMumbai.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonZkMainnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 6 of week ending 7/25/23 

- packages/react-app-revamp/components/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
- packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
- packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/index.tsx
- packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/PreviouslyDistributedReward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
- packages/react-app-revamp/hooks/useFundRewards/index.ts
- packages/react-app-revamp/hooks/useRewards/index.ts
- packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
- packages/react-app-revamp/styles/globals.css
> patch PR 7 of week ending 7/25/23

- packages/react-app-revamp/config/wagmi/custom-chains/baseMainnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
> patch PR 1 of week ending 8/1/23

- packages/forge/test/RewardsModule.t.sol
- packages/react-app-revamp/components/Header/MainHeader/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/luksoMainnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/luksoTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/helpers/alchemy.ts
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/store.tsx
- packages/react-app-revamp/hooks/useContest/v3/contracts.ts
- packages/react-app-revamp/hooks/useContestEvents/index.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useRewards/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/hooks/useUser/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/pages/404.tsx
> patch PR 2 of week ending 8/1/23

- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/store.tsx
- packages/react-app-revamp/lib/contests/index.ts
> merge sprint ending 8/1/23

- packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
- packages/react-app-revamp/config/wagmi/index.ts
- #471
- #472 
@seanmc9 have to merge this without review, prod is down for our main chains.
> patch PR 3 of week ending 8/8/23

- packages/react-app-revamp/config/wagmi/custom-chains/modeTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 1 of week ending 8/15/23

- packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
- packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/qChain.ts
- packages/react-app-revamp/config/wagmi/custom-chains/qChainTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 2 of week ending 8/15/23

- packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetwork.ts
> patch PR 4 for week ending 8/15/23

- packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
- packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
- packages/react-app-revamp/components/UI/Markdown/components/MarkdownOrderedList/index.tsx
- packages/react-app-revamp/components/UI/Markdown/components/MarkdownText/index.tsx
- packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/styles/globals.css
> patch PR 5 of week ending 8/15/23

- packages/react-app-revamp/config/wagmi/index.ts
forgot to add proteus to the index file.
> chain: add proteus pt2

- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 7 of week ending 8/15/23

- packages/react-app-revamp/config/wagmi/custom-chains/nautilusChain.ts
> patch PR 4 of week ending 8/22/23

- packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
- packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/ronin.ts
- packages/react-app-revamp/config/wagmi/custom-chains/roninTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
- packages/react-app-revamp/styles/globals.css
> patch PR 5 of week ending 8/22/23

- packages/react-app-revamp/config/wagmi/custom-chains/scrollSepoliaTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 6 of week ending 8/22/23

- packages/react-app-revamp/components/UI/ButtonV3/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/hooks/useAccountChange/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> enhancement: connect wallet info for submit and vote CTA

- packages/react-app-revamp/components/Header/MainHeader/index.tsx
This is just a tiny PR fixing spacing in the class declaration.
> bug: fix classes spacing issue

- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableRow/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/store.tsx
- packages/react-app-revamp/hooks/useContest/v3/contracts.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> patch PR 3 for week ending 8/29/23

- packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Closes #556 
This PR introduces a new page in our app `/submission` that behaves like a modal.
I'm just trying to optimize it now as if user open proposal through the UI, there is no need to fetch data as we already have that, we only need to fetch it when you visit a submission from the link.
> feat: add submissions page

- packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/fuse.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/v3/contracts.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> patch PR 5 for week ending 8/29/23

- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> merge sprint ending 8/29/23

- README.md
- packages/react-app-revamp/README.md
- packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
- packages/react-app-revamp/helpers/parseVotingCsv.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useUploadImage/index.tsx
- packages/react-app-revamp/lib/image/imgur/index.tsx
- packages/react-app-revamp/lib/vip/index.ts
- packages/react-app-revamp/supabase_schemas/user_permissions.sql
- packages/react-app-revamp/workers/parseSubmissionCsv.ts
- packages/react-app-revamp/workers/parseVotingCsv.ts
> patch PR 2 of week ending 9/5/23

- packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
> patch PR 4 of week ending 9/5/23

- packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Reverts jk-labs-inc/jokerace#571
Getting this error when going to this link https://jokerace.xyz/contest/arbitrumone/0xc1AD5102A357049f3e698248731e6A86f0F3a73d (https://jokerace-37jbymnpk-jokerace.vercel.app/contest/arbitrumone/0xc1AD5102A357049f3e698248731e6A86f0F3a73d for the preview of #571)
> Revert "enhancement: add meta tags to contest page"

- packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
> patch PR 5 of week ending 9/5/23

- packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
- packages/react-app-revamp/lib/contests/index.ts
> patch PR 1 of week ending 9/12/23

- packages/react-app-revamp/lib/contests/index.ts
> patch PR 2 of week ending 9/12/23

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
> patch PR 3 of week ending 9/12/23

- packages/react-app-revamp/components/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/components/_pages/Rewards/components/Create/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
> wording: update text on site

- packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
> enhancement: hard limit max submissions to 10k

- packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
> patch PR 1 of week ending 9/19/23

- packages/react-app-revamp/components/Parameters/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/base.ts
- packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
> patch PR 2 of week ending 9/19/23

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/config/routes/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> feat: redirect to submission after user submit

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/config/routes/index.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/helpers/timestamp.ts
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
- packages/react-app-revamp/hooks/useFundRewards/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/lib/analytics/participants/index.ts
- packages/react-app-revamp/lib/analytics/rewards/index.ts
- packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
- packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql
> patch PR 3 of week ending 9/19/23

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/base.ts
- packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
> hotfix: switch public node back to alchemy

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/base.ts
- packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
- packages/react-app-revamp/lib/contests/index.ts
> patch PR 4 of week ending 9/19/23

- packages/forge/test/Contest.t.sol
- packages/forge/test/RewardsModule.t.sol
> test: update test documentation and add basic release w deletions tests

- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
Closes #666 
as noted in #663, the EVM can't handle our sorting algorithm at greater than 1000 submissions.
> chore: update submission limit to 1k

- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
> patch PR 8 of week ending 9/19/23

- packages/react-app-revamp/supabase_schemas/contests_v3.sql
> enhancement: index contests_v3 + update schema

- packages/react-app-revamp/supabase_schemas/contests_v3.sql
> patch PR 9 of week ending 9/19/23

- packages/react-app-revamp/supabase_schemas/contest_participants_v3.sql
for a literal 99.9% decrese in execution time, lfj.
> enhancement: add participants table index

- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useProposal/index.ts
Closes #680 
There was a mismatch in structure when forming a proposals in v3 vs v2 version now, so we had to go back and accommodate.
Everything looks good now!
> bug: fix proposal structure for v2 contests

- packages/react-app-revamp/components/Parameters/index.tsx
> wording: add pluralization to params tab

- packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
> chore: switch out sepolia provider

- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
> wording: add text to voting allowlist page

- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
This PR includes small enhancement to dynamically set remaining proposal count for skeleton when user is trying to load more proposals.
> enhancement: dynamically set the count of remaining proposals for skeleton count

- packages/react-app-revamp/components/Parameters/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
- packages/react-app-revamp/helpers/getContestContractVersion.ts
- packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
- packages/react-app-revamp/helpers/timeout.ts
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/supabase_schemas/contest_participants_v3.sql
- #675 
- #681 
- #683 
- #685 
- #682 
- #686 
- #689
> merge sprint ending 9/19/23

- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
- packages/react-app-revamp/helpers/csvConstants.ts
- packages/react-app-revamp/helpers/csvTypes.ts
- packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
- packages/react-app-revamp/helpers/parseVotingCsv.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/workers/parseSubmissionCsv.ts
- packages/react-app-revamp/workers/parseVotingCsv.ts
Closes #668 
This PR solves circular dependency warning issue that we have locally, for the other error after i've did some research on react dos ( as suggested in the error ) it looks like this error has something to do with `Me` component, which we do not have in our codebase. 
It is most likely that this error is coming from some of the libraries that we have, i would leave it for now until we can gather more info.
> bug: fix circular dependency warning

- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
- packages/react-app-revamp/hooks/useProposalVotes/store.tsx
I have noticed that when you click load more on list of voters, whole list is being replaced with skeleton theme rather than remaining ones.
I've updated `ListProposalVotes` component to handle skeleton stuff gracefully.
> enhancement: add remaining count for list of voters on load more

- packages/react-app-revamp/components/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
> chore: update max proposal to 100 in order to create rewards module, keep hard limit at 1000

- packages/react-app-revamp/helpers/timeout.ts
> patch PR 4 of week ending 9/26/23

- packages/react-app-revamp/components/Rewards/index.tsx
now that we're audited it is no longer necessary!
> docs: rm unaudited note

- README.md
- packages/react-app-revamp/README.md
- packages/react-app-revamp/components/Rewards/index.tsx
> patch PR 5 of week ending 9/25/23

- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> enhancement: add description when user navigates to deleted proposals

- packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
- packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> patch PR 1 of week ending 10/3/23

- packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
specifically, update vote_amount to numeric for decimals and correct created_at to correctly be int4.
> chore: update schemas

- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/Countdown/index.tsx
> patch PR 1 of week ending 10/10/23

- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
Closes #738 
This PR's primary problem can be linked to the recent conditional block inclusion of the `ListProposalVotes` component. This block is intended to display particular features only when contest is in voting phase. This also explains why recently on some contest proposal voters would appear and on others it wouldn't.
Additionally, we included a minor modifications to the `ListProposalVotes` component to better encapsulate its functionality. This change aims to facilitate easier debugging and future changes to this component.
> bug: fix proposal voters missing in modal and small refactor on component

- packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
> bug: allow user to see if they are eligible to submit if wallet is not connected

- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> bug: add ellipsis on reward token symbol on contest page

- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 3 of week ending 10/10/23

- packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 4 of week ending 10/10/23

- packages/react-app-revamp/package.json
- packages/react-app-revamp/pages/_app.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
- packages/react-app-revamp/pages/index.tsx
- yarn.lock
> patch PR 5 of week ending 10/10/23

- packages/react-app-revamp/config/wagmi/index.ts
> chore: add bitget wallet

- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
- packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
- packages/react-app-revamp/lib/analytics/participants/index.ts
- packages/react-app-revamp/lib/analytics/rewards/index.ts
- packages/react-app-revamp/lib/user/index.tsx
- packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
- packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql
Closes #614 
In this PR we added `amount_withdrawn` column to rewards analytics table and `deleted` column to participants analytics table.
I've updated both codebase and dev & prod supabase to match following changes.
> feat: track withdrawals and deletes in analytics table

- packages/react-app-revamp/config/wagmi/custom-chains/scroll.ts
- packages/react-app-revamp/config/wagmi/index.ts
add scroll mainnet! announcement [here](https://x.com/scroll_zkp/status/1714267555307950451?s=46)!
> chain: add scroll mainnet

- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/scroll.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 1 of week ending 10/24/23

- packages/react-app-revamp/lib/user/index.tsx
> patch PR 3 of week ending 10/24/23

- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/Submission/index.tsx
> bugfix: fix add votes functionality on submission page

- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
> wording: add message when user is out of votes on proposal card

- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/components/_pages/ListContests/index.tsx
- packages/react-app-revamp/hooks/useSortedData/index.ts
- packages/react-app-revamp/pages/contests/index.tsx
- packages/react-app-revamp/pages/contests/live/index.tsx
- packages/react-app-revamp/pages/contests/past/index.tsx
- packages/react-app-revamp/pages/contests/upcoming/index.tsx
- packages/react-app-revamp/pages/user/[address]/index.tsx
- packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
- packages/react-app-revamp/pages/user/[address]/votes/index.tsx
> bugfix: separate sorting logic and remove stale times on list of contests

- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
- packages/react-app-revamp/lib/permissioning/index.ts
- packages/react-app-revamp/workers/nftOwnersProcessing.ts
> patch PR 2 of week ending 10/31/23

- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
Closes #831 
While i couldn't trigger this bug above, i've noticed that component which renders qualification message for submit can be refactored, let's keep an eye on it but codebase should be all clear now!
> bugfix: refactor qualification message for submitting a proposal

- packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
- packages/react-app-revamp/components/_pages/Create/utils/validation.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
Closes #876
In this PR, we implemented the logic and updated the design for the contest prompt tab. It's important to note that i intentionally set the placeholder text to "16px" for now, as i wouldn't use "20px" until we enhance proposal previews displayed in cards.
> enhancement: implement logic & design for new contest prompt

- packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
- packages/react-app-revamp/components/_pages/Create/utils/validation.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
> merge sprint ending 10/31/23

- packages/react-app-revamp/hooks/useDeployContest/index.ts
> patch PR 1 of week ending 11/7/23

- packages/react-app-revamp/helpers/getProposalId.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
> chore: use hash proposal fn for proposal id

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
- packages/react-app-revamp/styles/globals.css
> enhancement: implement design changes for entry charge in submission popup

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
> patch PR 4 of week ending 11/7/23

- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
> patch PR 5 of week ending 11/7/23

- packages/react-app-revamp/lib/monetization/index.ts
> patch PR 6 of week ending 11/7/23

- packages/react-app-revamp/pages/_app.tsx
@seanmc9 will merge this as users are reporting issues with voting!
> bugfix: wrap toast container with portal from headless ui

- packages/react-app-revamp/pages/_app.tsx
> patch PR 7 of week ending 11/7/23

- .github/workflows/auto_rebase_main_PRs.yml
> patch PR 8 of week ending 11/7/23

- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 9 of week ending 11/7/23

- packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
https://github.com/thirdweb-dev/js/blob/main/packages/chains/chains/10243.ts
> chain: add artheraTestnet

- .github/ISSUE_TEMPLATE/bug_report.md
The current bug report doesn't get the most essential info that we need to debug, most of the time people don't fill it all the way out (I don't really blame them haha, it's kind of technical and verbose), and we haven't updated it in a minute, so thought I'd try and renovate it a bit.
> docs: renovate the bug report

- .github/ISSUE_TEMPLATE/bug_report.md
Forgot to have the metadata at the top.
> chore: fix bug report

- packages/react-app-revamp/lib/analytics/rewards/index.ts
> chore: set reward actions to null if it isn't targeted action

- packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
- packages/react-app-revamp/styles/globals.css
Implementation from comments on #890
> enhancement: misc design updates

- packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
- packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
- packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/layouts/LayoutBase/index.tsx
- packages/react-app-revamp/pages/index.tsx
> chore: add burger menu to mobile

- packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
update schema to reflect changes made in #941
> chore: update amount sent schema to numeric

- .github/ISSUE_TEMPLATE/bug_report.md
- packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
- packages/react-app-revamp/components/UI/Toast/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/lib/analytics/participants/index.ts
- packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
- #939 
- #940 
- #938 
- #941 
- #943
> patch PR 1 of week ending 11/14/23

- packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/helpers/githubIssue.ts
Closes #945 
The following fields will automatically populate and be redirected to our bug report using the CTA we included to the error toast in this PR: 
- contest link
- wallet address
- error description
- device ( we only detect if desktop/tablet/mobile for now )
- browser name and version
> enhancement: bug reporting

- packages/react-app-revamp/components/Share/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
- packages/react-app-revamp/helpers/share.ts
- packages/react-app-revamp/hooks/useContest/store.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> enhancement: revamp text when sharing contest on social media

- packages/react-app-revamp/components/Share/index.tsx
- packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/helpers/githubIssue.ts
- packages/react-app-revamp/helpers/share.ts
- packages/react-app-revamp/hooks/useContest/store.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/lib/contests/index.ts
- packages/react-app-revamp/package.json
- packages/react-app-revamp/pages/user/[address]/index.tsx
- yarn.lock
- #948 
- #951 
- #952 
- #954
> patch PR 2 of week ending 11/14/23

- packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
- packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
- packages/react-app-revamp/hooks/useError/index.ts
- packages/react-app-revamp/utils/error.ts
- We changed link color and added underline on toast error
- We are catching `EstimateGasExecutionError` and `ContractFunctionExecutionError` as well
- Small refactor in multi step toast in order to dismiss it once error appears
> chore: update toast error style

- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/hooks/useProposal/store.tsx
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
> bugfix: add submissionsCount prop when user submit proposal

- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
> bugfix: prepare contract write in submit proposal

- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Since this forward icon can accomplish everything ( post to any social media + your most used applications), i don't think any of those icons are necessary for submission on mobile.
> enhancement: remove share icons in submission on mobile

- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/Legacy/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/hooks/useProposal/store.tsx
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/utils/error.ts
- #963 
- #968 
- #970 
- #966 
- #972
> merge sprint ending 11/14/24

- packages/react-app-revamp/config/wagmi/custom-chains/x1Testnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 3 of week ending 11/21/23

- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/hooks/useProposal/utils.ts
> patch PR 9 of week ending 11/21/23

- packages/react-app-revamp/hooks/useProposal/index.ts
> bugfix: only fetch proposals if more than 0 proposalIds

- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
> chore: move analytics sendoff up

- packages/react-app-revamp/components/UI/ButtonV3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
> patch PR 3 of week ending 11/28/23

- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/lib/analytics/participants/index.ts
- packages/react-app-revamp/utils/error.ts
> patch PR 4 of week ending 11/28/23

- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/hooks/useProposal/utils.ts
> patch PR 5 of week ending 11/28/23

- packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
- packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
Closes #863 
Hypothesized issue: once you click on a tab, there wasn't any loading component ( we would check if submission is null ) therefore, it would apply a little lag until that data comes back.
> chore: remove lag when clicking profile submissions or votes on first load

- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
- packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
- packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/qChainTestnet.ts
- packages/react-app-revamp/helpers/timeout.ts
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContestEvents/index.ts
- packages/react-app-revamp/hooks/useGenerateProof/index.ts
- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- #1022 
- #1058 
- #1056 
- #1055 
- #1054
> merge sprint ending 11/28/23

- packages/react-app-revamp/config/wagmi/custom-chains/holesky.ts
- packages/react-app-revamp/config/wagmi/custom-chains/redstoneHolesky.ts
- packages/react-app-revamp/config/wagmi/index.ts
https://redstone.xyz/docs/network-info
> chain: add holesky and redstoneHolesky

- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/SubmissionQualifierMessage/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/Submission/index.tsx
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useUser/index.ts
- packages/react-app-revamp/hooks/useUser/store.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Closes #1027 
TODO:
- ~~Increment my votes on submission when you add votes~~
- ~~Apply better UI for showing total votes of proposal~~
> feat: refactor user store and add total votes and used votes in proposal

- packages/react-app-revamp/workers/fetchDataFromBucket.ts
> patch PR 3 of week ending 12/5/23 

- packages/react-app-revamp/hooks/useTotalVotes/index.ts
> patch PR 4 of week ending 12/5/23

- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
> patch PR 5 of week ending 12/5/23

- package.json
- yarn.lock
Got this boi so thought may as well go ahead and bump version!
> chore: bump turbo to 1.11.0

- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
I will merge this PR in prod just to log these values and check if they aren't passed at time.
> bugfix: comments skeleton not showing

- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> patch PR 2 of week ending 12/12/23

- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> patch PR 3 of week ending 12/12/23

- packages/react-app-revamp/components/Comments/components/List/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> patch PR 4 of week ending 12/12/23

- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
> patch PR 6 of week ending 12/12/23

- packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/package.json
- yarn.lock
> bugfix: eval versions correctly

- packages/react-app-revamp/config/urql/index.ts
> bugfix: use lens v2 api

- packages/react-app-revamp/config/urql/index.ts
> patch PR 8 of week ending 12/12/23

- packages/react-app-revamp/config/wagmi/custom-wallets/luksoWallet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> chore: add universal profile wallet

- packages/react-app-revamp/components/Comments/components/Form/components/Input/components/SubmitButton/index.tsx
- packages/react-app-revamp/components/Comments/components/Form/components/Input/index.tsx
> enhancement: apply styles to mobile comment form

- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 11 of week ending 12/12/23

- packages/react-app-revamp/components/_pages/Submission/index.tsx
- packages/react-app-revamp/hooks/useProposal/index.ts
> enhancement: update next and prev buttons to follow proposal sort option

- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/Submission/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
- packages/react-app-revamp/hooks/useProposal/index.ts
> patch PR 12 of week ending 12/12/23

- packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
> fix tweet embedding if it contains text inside link

- packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
> patch PR 13 of week ending 12/12/23

- packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
accidentally left them in in #1140
> chore: rm accidentally left in logs

- packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
> patch PR 14 of week 12/12/23

- packages/react-app-revamp/components/UI/Slider/index.tsx
- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- yarn.lock
> patch PR 1 of week ending 12/19/23

- packages/react-app-revamp/utils/error.ts
> patch PR 3 of week ending 12/19/23

- packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
- packages/react-app-revamp/workers/generateProof.ts
> patch PR 5 of week ending 12/19/23

- packages/react-app-revamp/config/wagmi/custom-chains/astriaDusk2.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 8 of week ending 12/19/23

- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Just commenting out for now to patch prod, but will investigate further to figure out #1197
> bugfix: remove incorrect votes and rank from submission

- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
> patch PR 9 of week ending 12/19/23

- packages/react-app-revamp/config/wagmi/custom-chains/neon.ts
- packages/react-app-revamp/config/wagmi/custom-chains/neonDevnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
https://docs.neonevm.org/docs/developing/connect_rpc
> chain: add neon and neonDevnet

- packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
- packages/react-app-revamp/config/wagmi/custom-chains/evmosTestnet.ts
> patch PR 11 of week ending 12/19/23

- packages/react-app-revamp/components/Comments/components/Comment/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
- packages/react-app-revamp/hooks/useComments/index.ts
- packages/react-app-revamp/hooks/useComments/store.tsx
- packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
- packages/react-app-revamp/lib/analytics/participants/index.ts
- packages/react-app-revamp/lib/user/index.tsx
> chore: insert row in analytics table when proposal or comment is deleted

- packages/react-app-revamp/config/wagmi/custom-chains/frameTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
https://www.docs.frame.xyz/network_info/testnet
> chain: add frame testnet

- packages/react-app-revamp/config/wagmi/custom-chains/frameTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 1 of week ending 12/26/23

- packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
> bugfix: increase height of the fixed proposal preview container and fix image bug in proposal preview cards

- packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
> patch PR 2 of week ending 12/26/23

- packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/next.config.js
> patch PR 3 of week ending 12/26/23

- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/pages/_app.tsx
> patch PR 5 of week ending 12/26/23

- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/Submission/index.tsx
- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> patch PR 1 of week ending 1/2/24

- packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
- packages/react-app-revamp/hooks/useContractVersion/index.ts
catch the last cases of what we fixed in #1244
> chore: make rest of version vars strings

- packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
> patch PR 2 of week ending 1/16/23

- packages/react-app-revamp/config/wagmi/custom-chains/berachainTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 3 of week ending 1/16/23 

- packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
from discussion [here](https://x.com/arixoneth/status/1745461692438577153?s=20)
> chain: add taiko testnet

- packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 4 of week ending 1/16/23

- packages/react-app-revamp/components/Comments/components/List/index.tsx
- packages/react-app-revamp/components/Comments/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/Submission/index.tsx
- packages/react-app-revamp/hooks/useContractVersion/index.ts
- packages/react-app-revamp/hooks/useFetchProposalData/index.ts
- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
- packages/react-app-revamp/styles/globals.css
- packages/react-app-revamp/workers/parseVotingCsv.ts
> patch PR 5 of week ending 1/16/23

- packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
> patch PR 1 of week ending 1/23/24

- README.md
- packages/react-app-revamp/README.md
- packages/react-app-revamp/components/UI/AddToHomeScreen/components/NotSupportedBrowser/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/SuccessLayout/index.tsx
- packages/react-app-revamp/helpers/share.ts
- packages/react-app-revamp/pages/_app.tsx
we've been running into issues with Twitter blocking people posting our links and antivirus softwares flagging us, we've found out that that is a common issue with .xyz domains, we set up jokerace.io, and now are just going to point everything on our site to it!
> chore: switch to jokerace.io

- README.md
- packages/react-app-revamp/README.md
- packages/react-app-revamp/components/UI/AddToHomeScreen/components/NotSupportedBrowser/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/SuccessLayout/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/arthera.ts
- packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/helpers/share.ts
- packages/react-app-revamp/pages/_app.tsx
- packages/react-app-revamp/public/arthera.svg
> patch PR 2 of week ending 1/23/24

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Submission/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/Token/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/Token/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/hooks/useContestInfo/index.tsx
- packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
- packages/react-app-revamp/hooks/useTokenDetails/index.ts
- packages/react-app-revamp/lib/permissioning/index.ts
- packages/react-app-revamp/workers/nftOwnersProcessing.ts
- packages/react-app-revamp/workers/tokenHoldersProcessing.ts
Closes #1284 
@seanmc9 just got one question for `HARD_LIMIT` const, in case of NFTs we set it to 400k but in case of erc20 i set it up to 1 million, i think this should be higher than hard limit for NFTs, what do you think is the right number here?
> feat: erc20 permissions

- packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Submission/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/Token/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/Token/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/helpers/share.ts
- packages/react-app-revamp/hooks/useContestInfo/index.tsx
- packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
- packages/react-app-revamp/hooks/useTokenDetails/index.ts
- packages/react-app-revamp/lib/permissioning/index.ts
- packages/react-app-revamp/pages/_app.tsx
- packages/react-app-revamp/workers/nftOwnersProcessing.ts
- packages/react-app-revamp/workers/tokenHoldersProcessing.ts
> patch PR 3 of week ending 1/23/24

- packages/react-app-revamp/hooks/useDeployContest/index.ts
> chore: apply lowercase contract address in supabase

- packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
> patch PR 2 of week ending 2/6/24

- packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
We currently do not need decimal check as number input component isn't used where decimal check is needed.
> bugfix: remove decimal check from number input

- packages/react-app-revamp/hooks/useCastVotes/index.ts
> bugfix: add percentage to creator value for vote cast analytics

- packages/react-app-revamp/config/wagmi/custom-chains/syndicateFrame.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/hooks/useCastVotes/index.ts
> patch PR 2 of week ending 2/20/24

- packages/react-app-revamp/hooks/useUploadImage/index.tsx
- packages/react-app-revamp/lib/image/imgur/index.tsx
> patch PR 4 of week ending 2/20/24 

- packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
> patch PR 5 of week ending 2/20/24

- packages/react-app-revamp/components/Header/LandingHeader/index.tsx
- packages/react-app-revamp/pages/404.tsx
- packages/react-app-revamp/pages/_app.tsx
- packages/react-app-revamp/pages/index.tsx
- packages/react-app-revamp/public/manifest.json
> merge sprint ending 2/20/24

- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Timing/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
> patch PR 1 of week ending 2/27/24

- packages/react-app-revamp/config/wagmi/custom-chains/blastTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
https://docs.blast.io/using-blast
> chain: add blast testnet

- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/components/Submitters/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/blastTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 3 of week ending 2/27/24

- packages/react-app-revamp/config/wagmi/custom-chains/ancient8.ts
- packages/react-app-revamp/config/wagmi/custom-chains/ancient8Testnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
https://docs.ancient8.gg/using-ancient8-chain/network-information#ancient8-mainnet
> chain: add ancient 8 testnet and mainnet

- packages/react-app-revamp/config/wagmi/custom-chains/ancient8.ts
- packages/react-app-revamp/config/wagmi/custom-chains/ancient8Testnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 4 of week ending 2/27/24

- packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
> patch PR 2 of week ending 3/5/24 

- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 4 of week ending 3/5/24

- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
> bugfix: fix parsing of submission cost

- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
> patch PR 5 of week ending 3/5/24

- packages/react-app-revamp/config/wagmi/custom-chains/blast.ts
- packages/react-app-revamp/config/wagmi/custom-chains/dymension.ts
- packages/react-app-revamp/config/wagmi/index.ts
- https://docs.blast.io/building/network-information#additional-public-rpc-endpoints
- https://dymension.xyz/
> chain: add blast and dymension

- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
Closes #1347
Let's merge #1434 first since there will be a conflict
> feat: add contact field in description page

- packages/react-app-revamp/package.json
- yarn.lock
https://x.com/_jxom/status/1767290101162483956?s=20
> chore: update viem

- packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
- packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useSearchNfts/index.ts
- packages/react-app-revamp/hooks/useTokenList/index.ts
> patch PR 1 of week ending 3/19/24

- packages/react-app-revamp/components/ChargeLayout/index.tsx
- packages/react-app-revamp/hooks/useCastVotes/index.ts
> patch 2 of week ending 3/19/24

- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/helpers/isContentTweet.ts
- packages/react-app-revamp/hooks/useProposal/store.tsx
- packages/react-app-revamp/hooks/useProposal/utils.ts
- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/styles/globals.css
Closes #1440
|**Before**|**After**|
|:---:|:---:|
|  ![before](https://github.com/jk-labs-inc/jokerace/assets/18723426/e741593d-14be-43b2-a5fa-bb6c30af3099)| ![after](https://github.com/jk-labs-inc/jokerace/assets/18723426/e00e5494-9c45-4ee8-97c3-12af3cd2e13a) |
> feat: embed tweet in proposal preview

- packages/forge/test/Contest.t.sol
was getting warnings in the compiler so just going to appease it
> chore: make test funcs view

- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
> patch PR 4 of week ending 3/26/24

- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/pages/_app.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
- packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
- packages/react-app-revamp/pages/contest/new/index.tsx
- packages/react-app-revamp/pages/contests/index.tsx
- packages/react-app-revamp/pages/contests/live/index.tsx
- packages/react-app-revamp/pages/contests/past/index.tsx
- packages/react-app-revamp/pages/contests/upcoming/index.tsx
- packages/react-app-revamp/pages/index.tsx
- packages/react-app-revamp/pages/user/[address]/comments/index.tsx
- packages/react-app-revamp/pages/user/[address]/index.tsx
- packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
- packages/react-app-revamp/pages/user/[address]/votes/index.tsx
> patch PR 7 of week ending 3/26/24

- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
> wording: update anyone can vote

- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/UnsupportedChain/index.tsx
> enhancement: apply monetization page text change

- packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/Buttons/Submit/index.tsx
- packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
- packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
- packages/react-app-revamp/hooks/useFundRewards/index.ts
> bugfix: fix funding pool for erc20 tokens on base

- packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
- packages/react-app-revamp/hooks/useDeployContest/types/index.ts
- packages/react-app-revamp/hooks/useSearchNfts/index.ts
- packages/react-app-revamp/lib/permissioning/index.ts
- packages/react-app-revamp/workers/nftOwnersProcessing.ts
> feat: add erc1155 permission in create flow

- packages/react-app-revamp/hooks/useProfileData/index.ts
- packages/react-app-revamp/public/contest/user.svg
> enhancement: use generic user icon for profile

- packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
- packages/react-app-revamp/hooks/useDeployContest/types/index.ts
- packages/react-app-revamp/hooks/useProfileData/index.ts
- packages/react-app-revamp/hooks/useSearchNfts/index.ts
- packages/react-app-revamp/lib/permissioning/index.ts
- packages/react-app-revamp/public/contest/user.svg
- packages/react-app-revamp/workers/nftOwnersProcessing.ts
> merge sprint ending 3/26/24

- packages/react-app-revamp/hooks/useSearchNfts/index.ts
> patch PR 1 of week ending 4/2/24

- packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
- packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
- packages/react-app-revamp/hooks/useDeployContest/types/index.ts
- packages/react-app-revamp/hooks/useSearchNfts/index.ts
- packages/react-app-revamp/lib/permissioning/index.ts
- packages/react-app-revamp/workers/nftOwnersProcessing.ts
> patch PR 2 of week ending 4/2/24

- packages/react-app-revamp/styles/globals.css
> patch PR 3 of week ending 4/2/24

- packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/gold.ts
- packages/react-app-revamp/config/wagmi/index.ts
> chain: add gold

- packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
- packages/react-app-revamp/config/wagmi/custom-chains/gold.ts
- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 2 of week ending 4/9/24

- packages/react-app-revamp/config/wagmi/index.ts
this was a blocker for the Nance integration
> chore: add safe wallet

- packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
> merge sprint ending 4/9/24

- packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/components/Card/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Bello/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Coinvise/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/HatsProtocol/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Nance/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/types.ts
- packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
- packages/react-app-revamp/hooks/useBello/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/store.tsx
- packages/react-app-revamp/hooks/useExtensions/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/lib/extensions/index.ts
- packages/react-app-revamp/supabase_schemas/extensions.sql
> feat: add extensions

- packages/react-app-revamp/package.json
- yarn.lock
Just getting rid of this warning
> chore: clean up build

- packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
- packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
implementing frame metadata per https://frog.fm/platforms/next#bonus-page--frame-co-location
> chore: add frame metadata

- packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
- packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
> patch PR 1 of week ending 4/23/24

- packages/react-app-revamp/app/api/[[...routes]]/route.tsx
- packages/react-app-revamp/lib/frames/submission/index.ts
- packages/react-app-revamp/lib/frames/voting/index.ts
> patch PR 3 of week ending 4/23/24 

- packages/react-app-revamp/app/api/[[...routes]]/route.tsx
- packages/react-app-revamp/components/Frames/submission/Allowlisted/index.tsx
- packages/react-app-revamp/components/Frames/submission/FinalFrame/index.tsx
- packages/react-app-revamp/components/Frames/submission/InitialFrame/index.tsx
- packages/react-app-revamp/components/Frames/submission/Timing/index.tsx
- packages/react-app-revamp/components/Frames/submission/UnsupportedChain/index.tsx
- packages/react-app-revamp/components/Frames/transactions/success/index.tsx
- packages/react-app-revamp/components/Frames/vote/Allowlisted/index.tsx
- packages/react-app-revamp/components/Frames/vote/FinalFrame/index.tsx
- packages/react-app-revamp/components/Frames/vote/InitialFrame/index.tsx
- packages/react-app-revamp/components/Frames/vote/SubmissionDeleted/index.tsx
- packages/react-app-revamp/components/Frames/vote/Timing/index.tsx
- packages/react-app-revamp/components/Frames/vote/UnsupportedChain/index.tsx
> patch PR 4 of week ending 4/23/24

- packages/react-app-revamp/layouts/LayoutBase/index.tsx
> patch PR 5 of week ending 4/23/24

- packages/react-app-revamp/app/api/[[...routes]]/route.tsx
> patch PR 6 of week ending 4/23/24

- packages/react-app-revamp/hooks/useUser/index.ts
> bugfix: fix submitters and voters info in params tab

- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/HatsProtocol/index.tsx
> patch PR 8 of week ending 4/23/24

- packages/react-app-revamp/styles/globals.css
> patch PR 3 of week ending 4/30/24

- packages/react-app-revamp/hooks/useProfileData/index.ts
I have noticed that for some user profiles, it would take too long for them to load. It is all due to `getEnsAvatar` function which sometimes takes too long to return avatar URI for specific ENS name.
I have implemented a race condition in which for that specific cases, we would wait 10 seconds to grab URI, if it takes longer, we would render `DEFAULT_AVATAR_URL`
Another issue is, that avatars which are stored on ipfs would fail sometimes ( also rare case ), there is a way to provide `assetGatewayUrls ` but we would ideally need to setup cloudfare ipfs, which has a free option that could suit us for now.
> chore: implement race condition in getEnsAvatar fn

- packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useProfileData/index.ts
- packages/react-app-revamp/styles/globals.css
- packages/react-app-revamp/workers/parseVotingCsv.ts
- #1587
- #1585 
- #1582 
- #1581
> patch PR 4 of week ending 4/30/24

- packages/react-app-revamp/components/Frames/submission/FinalFrame/index.tsx
- packages/react-app-revamp/components/Frames/vote/FinalFrame/index.tsx
- packages/react-app-revamp/lib/frames/utils.ts
- packages/react-app-revamp/package.json
- yarn.lock
> patch PR 5 of week ending 4/30/24

- packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Timeline/index.tsx
> enhancement: streamline contest page

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
> patch PR 1 of week ending 5/28/24

- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> patch PR 2 of week ending 5/28/24

- packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> patch PR 4 of week ending 5/28/24

- packages/react-app-revamp/config/wagmi/custom-chains/taiko.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> patch PR 5 of week ending 5/28/24 

- funding.json
> chore: add retro funding config

- packages/react-app-revamp/config/wagmi/custom-chains/ham.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
https://docs.ham.fun/docs/network-information
> chain: add ham chain

- packages/react-app-revamp/config/wagmi/custom-chains/ham.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> patch PR 2 of week ending 6/11/24

- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
> enhancement: clarify my votes for anyone can vote on contest page

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
> chore: clarify pay per vote vs per tx in params tab

- packages/react-app-revamp/hooks/useDeployRewards/index.ts
> patch PR 2 of week ending 6/18/24

- packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
> chore: use alchemy for sepolia rpc

- packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
> patch PR 4 of week ending 6/18/24

- packages/react-app-revamp/lib/contests/index.ts
> patch PR 5 of week ending 6/18/24

- packages/forge/package.json
- packages/forge/test/Contest.t.sol
- packages/forge/test/RewardsModule.t.sol
> merge sprint ending 6/18/24

- package.json
- packages/forge/package.json
- yarn.lock
finish up removing the ^s as started in #1668
> chore: rm rest of carats

- packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add goerli back

- packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> patch PR 2 of week ending 6/25/24 

- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Stack/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/index.tsx
Closes #1615
I am still unable to issue points with jokerace integration though, stack found a contest but i am stuck with loading of the contest.
> enhancement: add stack extension

- packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
> chore: change sei chain id

- packages/forge/package.json
- packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #1703 
- #1704 
- #1706 
- #1707 
- #1708
- #1710 
- #1711 
- #1712 
- #1713 
- #1714 
- #1717 
- #1718
- #1719 
- #1721 
- #1725
> patch 3 of week ending 7/2/24

- packages/react-app-revamp/config/wagmi/custom-chains/seiTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
https://chainlist.org/?search=sei&testnets=true
> chain: add sei testnet

- packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
- packages/react-app-revamp/config/wagmi/custom-chains/seiTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> patch PR 6 of week ending 7/2/24

- renovate.json
https://docs.renovatebot.com/configuration-options/#automergestrategy
> chore: make automerge squashed

- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/package.json
- yarn.lock
- #1776
- #1774 
- #1772 
- #1779
> merge sprint ending 7/2/24

- package.json
https://stackoverflow.com/questions/77897612/problem-when-trying-to-add-prettiers-git-hook-husky-install-error-install-com
> chore: husky install deprecated

- packages/react-app-revamp/components/Share/index.tsx
- packages/react-app-revamp/components/Sort/index.tsx
- packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
- packages/react-app-revamp/components/TokenSearchModal/index.tsx
- packages/react-app-revamp/components/UI/AddToHomeScreen/index.tsx
- packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
- packages/react-app-revamp/components/UI/Deployment/Ethereum/index.tsx
- packages/react-app-revamp/components/UI/DialogModal/index.tsx
- packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
- packages/react-app-revamp/components/UI/Dropdown/index.tsx
- packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
- packages/react-app-revamp/components/UI/ToggleSwitch/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/Duplicates/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Submission/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
HeadlessUI v2 has a new API that we need to use, currently our app works but all of the elements are deprecated in the favor of new ones.
> chore: adapt HeadlessUI v2 api

- packages/react-app-revamp/app/api/[[...routes]]/route.tsx
- packages/react-app-revamp/components/_pages/Create/utils/csv.ts
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
- packages/react-app-revamp/helpers/ethers.ts
- packages/react-app-revamp/helpers/getBlock.ts
- packages/react-app-revamp/helpers/getContestContractVersion.ts
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useContestEvents/index.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployRewards/index.ts
- packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
- packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
- packages/react-app-revamp/lib/participants/index.ts
- packages/react-app-revamp/package.json
- packages/react-app-revamp/workers/generateProof.ts
- yarn.lock
reverting #1809 until @nakedfool is back from time off to minimize risk in the interrim.
will pick up again with #1847
> chore: revert #1809

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Dropdown/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/AddTokenWidget/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
> enhancement: rewards flow tweaks

- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
Closes #1784
In terms of font size, i think the confirmation page 16px is visually appealing to read! Although i believe that 18 pixels is a bit too much, i'm willing to test it in production with everyone if you are all up for it.
> enhancement: confirmation page

- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
> enhancement: rm read more when voting opened or closed

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Dropdown/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/AddTokenWidget/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
> patch PR 2 of week ending 7/16/24

- package.json
- packages/react-app-revamp/package.json
- yarn.lock
- #1862 
- #1863 
- #1864 
- #1866 
- #1867 
- #1869 
- #1870 
- #1873
- #1874 
- #1875 
- #1876 
- #1872 
- #1871 
- #1878
> patch PR 1 of week ending 7/23/24

- packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/avalanche.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #1965
- #1964 
- #1963 
- #1967
> patch PR 1 of week ending 8/6/24

- packages/react-app-revamp/app/user/[address]/comments/page.tsx
- packages/react-app-revamp/app/user/[address]/submissions/page.tsx
- packages/react-app-revamp/app/user/[address]/votes/page.tsx
- packages/react-app-revamp/components/_pages/ListContests/index.tsx
- packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
- packages/react-app-revamp/components/_pages/User/components/Skeleton/index.tsx
- packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
- packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
- packages/react-app-revamp/layouts/LayoutUser/index.tsx
- packages/react-app-revamp/lib/contests/index.ts
- packages/react-app-revamp/lib/user/index.tsx
Here are some of the improvements / optimizations for the user profile page in this PR: 
- Using `ilike` instead of `eq` in database queries to handle case-sensitive cases for user addresses in the case of a failure.
- Improved pagination experience: static elements like pagination controls remain visible during data loading which ends in better visual orientation.
- Implemented `Suspense` for tab switching (contests, submissions, votes, and comments), resulting in instant tab changes ( old issue i think )
> chore: user profile page optimizations

- packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
- packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
- packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
- packages/react-app-revamp/lib/user/index.tsx
> patch PR 3 of week ending 8/6/24

- packages/react-app-revamp/components/_pages/Create/templates/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/karaoke-challenge/config.ts
- packages/react-app-revamp/components/_pages/Create/templates/karaoke-challenge/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/templates.ts
- packages/react-app-revamp/components/_pages/Create/templates/types.ts
> enhancement: add karaoke challenge template

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Submitters/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Voters/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
- packages/react-app-revamp/hooks/useSubmitters/index.ts
- packages/react-app-revamp/hooks/useUser/index.ts
- packages/react-app-revamp/hooks/useVoters/index.ts
> bugfix: resolve BSOD for non-v3 contests

- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Closes #2039 
This one was relatively easy as we already have this logic in app, we just needed to add `chainName` and apply some different colors to the elements.
> enhancement: add insufficient balance per chain of the contest small design updates

- packages/react-app-revamp/config/wagmi/custom-chains/forma.ts
- packages/react-app-revamp/config/wagmi/custom-chains/formaTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add forma and formaTestnet

- .github/ISSUE_TEMPLATE/chain_request.md
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/forma.ts
- packages/react-app-revamp/config/wagmi/custom-chains/formaTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #2070 
- #2071 
- #2072 
- #2073
- #2076
> patch PR 4 of week ending 8/13/24

- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
> chore: move metadata to description tab in create flow

- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
- packages/react-app-revamp/package.json
- yarn.lock
> patch PR 1 of week ending 8/20/24

- packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
> chore: update evmos rpc

- packages/react-app-revamp/components/Comments/components/Comment/index.tsx
- packages/react-app-revamp/components/UI/GradientText/index.tsx
- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/List/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/CancelContest/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/CancelContest/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
- packages/react-app-revamp/hooks/useContestState/index.ts
- packages/react-app-revamp/hooks/useContestState/store.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> enhancement: cancel contests

- package.json
- packages/react-app-revamp/components/Comments/components/Comment/index.tsx
- packages/react-app-revamp/components/UI/GradientText/index.tsx
- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/List/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/CancelContest/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/CancelContest/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
- packages/react-app-revamp/hooks/useContestState/index.ts
- packages/react-app-revamp/hooks/useContestState/store.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- yarn.lock
> patch PR 2 of week ending 8/20/24

- packages/react-app-revamp/components/UI/DialogModalV4/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Timeline/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/CancelContest/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/index.tsx
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useContestState/index.ts
- packages/react-app-revamp/hooks/useCreatorSplitDestination/index.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/types/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/styles/globals.css
> feat: edit earnings

- packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
> wording: update rewards tie explanation

- packages/react-app-revamp/.vercelignore
> chore: rm .vercelignore

- packages/react-app-revamp/helpers/timeout.ts
> patch PR 3 of week ending 8/27/24 

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/DeploymentStatus/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
- packages/react-app-revamp/hooks/useDeployRewards/index.ts
> patch PR 4 of week ending 8/27/24

- packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
- packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
- packages/react-app-revamp/components/Header/LandingHeader/index.tsx
- packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
> bugfix: fix window undefined on component load

- packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
> bugfix: fix scroll in template dropdown in create flow on mobile

- packages/react-app-revamp/components/Header/LandingHeader/index.tsx
> enhancement: moving up logo and wallet on landing page

- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/package.json
- yarn.lock
> patch PR 7 of week ending 8/27/24

- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
> patch PR 8 of week ending 8/27/24

- packages/react-app-revamp/helpers/timeout.ts
- packages/react-app-revamp/package.json
- yarn.lock
> patch PR 9 of week ending 8/27/24

- packages/react-app-revamp/lib/rewards/index.ts
quickfixes #2228 - should go in again next week and fix more thoroughly though
> bugfix: quickfix rewards rounding issue

- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> bugfix: replace useRouter with window.location.reload for more reliable page reload

- packages/react-app-revamp/app/api/token/route.ts
> bugfix: enhance token search to prioritize symbol matches

- packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
> enhancement: add rewards module address link in rewards tab

- packages/react-app-revamp/app/api/token/route.ts
- packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/helpers/isContentTweet.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
- packages/react-app-revamp/package.json
- yarn.lock
- #2260 
- #2262
- #2263
- #2264
- #2265
- #2267
> patch PR 4 of week ending 9/3/24

- packages/react-app-revamp/hooks/useProposal/index.ts
> bugfix: use server config in fetch single proposal fn

- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/package.json
- yarn.lock
> patch PR 2 of week ending 9/10/24 

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/CancelRewards/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/CancelRewards/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasableRewards/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
- packages/react-app-revamp/hooks/useCancelRewards/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> feat: add cancel rewards functionality

- packages/react-app-revamp/hooks/useDeployContest/store.tsx
> bugfix: add default submissions const in store

- packages/react-app-revamp/hooks/useDeployContest/store.tsx
> patch PR 1 of week ending 9/17/24

- packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
- packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
> bugfix: get rid of hydration error for user profile

- packages/react-app-revamp/hooks/useDeployContest/index.ts
was supposed to be included in #2328 so just patching in after
> chore: rm redundant const

- packages/react-app-revamp/hooks/useContest/index.ts
> bugfix: fix charge settings for non monetized chains

- packages/react-app-revamp/config/wagmi/custom-chains/fhenixHeliumTestnet.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add fhenix helium testnet

- packages/react-app-revamp/app/api/token/route.ts
I have noticed that this list https://tokenlistooor.com/list/popular has overall a better list of tokens and is curated better than the previous one!
> chore: use popular list of tokens for token search modal

- packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
> enhancement: increase font size for titles on landing page

- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
> bugfix: add chainId to delete proposals fn

- packages/react-app-revamp/components/UI/Toast/components/Info/index.tsx
- packages/react-app-revamp/components/UI/Toast/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/components/Submitters/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
> feat: add only me option for entering the contest

- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
> enhancement: prompt users to connect wallet on vote

- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
> enhancement: update rewards analytics calculation with creator percentage

- packages/react-app-revamp/components/Comments/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
> enhancement: remove comments toggle

- packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
> wording: apply different language for submit button on contest page for mobile

- packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
- packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
- packages/react-app-revamp/lib/contests/index.ts
> enhancement: showcase canceled contests in the UI

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasableRewards/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasedRewards/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/TotalRewardsInfo/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
- packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
- packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
- packages/react-app-revamp/components/_pages/RewardsPreviouslyDistributedTable/index.tsx
- packages/react-app-revamp/helpers/formatBalance.ts
- packages/react-app-revamp/hooks/useReleasableRewards/index.ts
- packages/react-app-revamp/hooks/useReleasedRewards/index.ts
- packages/react-app-revamp/lib/contests/index.ts
> enhancement: showcase full rewards

- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
> patch PR 2 of week ending 10/1/24

- packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/ContestVisibility/index.tsx
> enhancement: edit info message on setting contest visibility

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/index.tsx
- packages/react-app-revamp/tailwind.config.js
> enhancement: add self funding option in create flow

- packages/react-app-revamp/config/wagmi/custom-chains/boba.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add boba

- packages/react-app-revamp/config/wagmi/custom-chains/boba.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> patch PR 5 of week ending 10/1/24

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
> enhancement: add textarea in metadata string fields

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
- packages/react-app-revamp/package.json
- yarn.lock
> merge sprint ending 10/1/24

- packages/react-app-revamp/package.json
- yarn.lock
> patch PR 3 of week ending 10/8/24

- packages/react-app-revamp/config/wagmi/custom-chains/zeta.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add zetachain

- packages/react-app-revamp/app/api/bucket/load/route.ts
- packages/react-app-revamp/app/api/contest-exists/route.ts
- packages/react-app-revamp/app/api/contest/check-allowlist-permission/route.ts
- packages/react-app-revamp/app/api/contest/get-details-by-address/route.ts
- packages/react-app-revamp/app/api/contest/jklabs-split-destination-address/route.ts
- packages/react-app-revamp/app/api/contest/requirements-data/route.ts
- packages/react-app-revamp/app/api/contests/featured/route.ts
- packages/react-app-revamp/app/api/contests/live/route.ts
- packages/react-app-revamp/app/api/contests/participant-data/route.ts
- packages/react-app-revamp/app/api/contests/past/route.ts
- packages/react-app-revamp/app/api/contests/search/route.ts
- packages/react-app-revamp/app/api/contests/upcoming/route.ts
- packages/react-app-revamp/app/api/extensions/route.ts
- packages/react-app-revamp/app/api/monetization/charge-details/route.ts
- packages/react-app-revamp/app/api/rewards/token-addresses/route.ts
- packages/react-app-revamp/app/api/subscribe/is-subscribed/route.ts
- packages/react-app-revamp/app/api/token/route.ts
- packages/react-app-revamp/app/api/tweet/[id]/route.ts
- packages/react-app-revamp/app/api/user/allowed-to-submit/route.ts
- packages/react-app-revamp/app/api/user/allowed-to-vote/route.ts
- packages/react-app-revamp/app/api/user/comments/route.ts
- packages/react-app-revamp/app/api/user/contests/route.ts
- packages/react-app-revamp/app/api/user/submissions/route.ts
Closes #2582
We are setting it to `force-dynamic` as suggested by the nextjs community. 
You can look at more details in their docs - https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
> chore: disable caching for all api get routes

- packages/react-app-revamp/app/api/bucket/load/route.ts
- packages/react-app-revamp/app/api/contest-exists/route.ts
- packages/react-app-revamp/app/api/contest/check-allowlist-permission/route.ts
- packages/react-app-revamp/app/api/contest/get-details-by-address/route.ts
- packages/react-app-revamp/app/api/contest/jklabs-split-destination-address/route.ts
- packages/react-app-revamp/app/api/contest/requirements-data/route.ts
- packages/react-app-revamp/app/api/contests/featured/route.ts
- packages/react-app-revamp/app/api/contests/live/route.ts
- packages/react-app-revamp/app/api/contests/participant-data/route.ts
- packages/react-app-revamp/app/api/contests/past/route.ts
- packages/react-app-revamp/app/api/contests/search/route.ts
- packages/react-app-revamp/app/api/contests/upcoming/route.ts
- packages/react-app-revamp/app/api/extensions/route.ts
- packages/react-app-revamp/app/api/monetization/charge-details/route.ts
- packages/react-app-revamp/app/api/rewards/token-addresses/route.ts
- packages/react-app-revamp/app/api/subscribe/is-subscribed/route.ts
- packages/react-app-revamp/app/api/token/route.ts
- packages/react-app-revamp/app/api/tweet/[id]/route.ts
- packages/react-app-revamp/app/api/user/allowed-to-submit/route.ts
- packages/react-app-revamp/app/api/user/allowed-to-vote/route.ts
- packages/react-app-revamp/app/api/user/comments/route.ts
- packages/react-app-revamp/app/api/user/contests/route.ts
- packages/react-app-revamp/app/api/user/submissions/route.ts
> patch PR 8 of week ending 10/8/24

- packages/react-app-revamp/app/api/token/route.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useEmailSignup/index.tsx
- packages/react-app-revamp/hooks/useUser/index.ts
- packages/react-app-revamp/lib/buckets/index.tsx
- packages/react-app-revamp/lib/contests/index.ts
- packages/react-app-revamp/lib/extensions/index.ts
- packages/react-app-revamp/lib/monetization/index.ts
- packages/react-app-revamp/lib/rewards/index.ts
- packages/react-app-revamp/lib/user/index.tsx
- packages/react-app-revamp/lib/vip/index.ts
> patch PR 9 of week ending 10/8/24

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Timeline/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/DeploymentStatus/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/UnsupportedChain/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
- packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
> wording: update language from earnings to charges

- packages/react-app-revamp/components/_pages/FeaturedContests/index.tsx
- packages/react-app-revamp/components/_pages/Landing/components/index.tsx
- packages/react-app-revamp/lib/contests/constants/index.ts
> chore: bump featured to 8

- packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
- packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
> bugfix: get alchemy base url in user tokens hook

- packages/react-app-revamp/app/layout.tsx
- packages/react-app-revamp/app/portal.tsx
In this PR we fixed a situation where users couldn't click on toast inside a modal, before this it required users to close a modal and click on a toast.
> bugfix: enable toast interaction when modal is open

- packages/react-app-revamp/hooks/useUser/index.ts
> bugfix: update userVotes calculation to account for gas costs separately

- packages/react-app-revamp/config/wagmi/custom-chains/boba.ts
previous rpc was rate-limiting us as mentioned in #2646, let's see if this new one will be stable
> chain: update boba rpc

- packages/react-app-revamp/hooks/useChargeDetails/index.ts
- packages/react-app-revamp/lib/monetization/index.ts
- packages/react-app-revamp/supabase_schemas/chain_params.sql
> feat: add default value for entry and vote

- packages/react-app-revamp/config/wagmi/custom-chains/gnosis.ts
previous one was rate-limiting us.
> chain: switch gnosis rpc provider

- packages/react-app-revamp/supabase_schemas/contests_v3.sql
> feat: track has been featured

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
- packages/react-app-revamp/config/wagmi/custom-chains/base.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
> bugfix: prevent rate-limiting

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
- packages/react-app-revamp/config/wagmi/custom-chains/base.ts
- packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
- packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
- packages/react-app-revamp/supabase_schemas/contests_v3.sql
> patch PR 4 of week ending 10/15/24

- packages/react-app-revamp/lib/contests/index.ts
- packages/react-app-revamp/lib/user/index.tsx
> chore: read contest title from chain across site

- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
> feat: show number of voters on an entry

- packages/react-app-revamp/hooks/useUser/index.ts
I have noticed that for [this](https://www.jokerace.io/contest/avalanche/0x5bc588511a1277c215cf81dafa0764956dfeddbd) contest, in the params page, it is showing that i have negative votes ( "you have -2 votes" ) 
We should add conditional in `checkAnyoneCanVoteUserQualification ` fn to check if user balance is equal to zero, and if it is, we can do an early return there.
> bugfix: early return for zero balance in checkAnyoneCanVoteUserQualification fn

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
https://docs.arbitrum.io/build-decentralized-apps/reference/node-providers
> chore: move to public arb rpc

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
closes #2722 - that RPC rate-limits/isn't production scale
> chore: revert arb rpc

- packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
> patch PR 2 of week ending 10/22/24

- packages/react-app-revamp/config/wagmi/custom-chains/morph.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add morph

- packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
- packages/react-app-revamp/lib/proposal/index.ts
> patch PR 3 of week ending 10/29/24

- packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
closes #2812 
completes the update that #2757 should have been
> chain: update camp v2

- packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
> patch PR 4 of week ending 10/29/24

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
> enhancement: update voting info in params tab

- packages/react-app-revamp/components/Header/LandingHeader/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/layouts/LayoutBase/index.tsx
> chore: add faq to footer

- packages/react-app-revamp/lib/monetization/index.ts
> chore: auto enable monetization on all testnet chains

- packages/react-app-revamp/components/Header/LandingHeader/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/layouts/LayoutBase/index.tsx
- packages/react-app-revamp/lib/monetization/index.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #2814 
- #2764 
- #2818 
- #2817 
- #2816
> merge sprint ending 10/29/24 

- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
> patch PR 1 of week ending 11/5/24

- packages/react-app-revamp/hooks/useDeployContest/index.ts
Currently, users would encounter an error stating that the jklabs address could not be fetched while attempting to launch an anyone-can-vote contest on a testnet ( besides sepolia since we have it in `chains_params` )
The problem is that during the deployment process, we use the `chain_params` table to retrieve the jklabs address based on that chain; however, because testnets are not present in that table, the address could not be located. In the event of a testnet, i suggest that we simply set to our default hardcoded address.
I apologise for not testing this end-to-end; i completely overlooked this step in the deployment procedure.
> bugfix: do not fetch jklabs address from chains_params if chain is testnet

- packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
- packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
- packages/react-app-revamp/components/UI/ImageUpload/index.tsx
- packages/react-app-revamp/components/UI/ImageUpload/utils.ts
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Preview/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
- packages/react-app-revamp/components/_pages/Create/utils/validation.ts
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/Editor/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageLayout/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/Buttons/Delete/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
> enhancement: apply entry preview enhancements

- packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
https://docs.hedera.com/hedera/core-concepts/smart-contracts/deploying-smart-contracts/json-rpc-relay#community-hosted-json-rpc-relays
> chain: update hedera rpc

- packages/react-app-revamp/hooks/useProposal/utils.ts
- packages/react-app-revamp/lib/proposal/index.ts
> bugfix: add default metadata fields in constructor

- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
- packages/react-app-revamp/hooks/useProposal/utils.ts
- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #2839 
- #2840 
- #2843 
- #2842 
- #2841
> patch PR 3 of week ending 11/5/24

- .github/ISSUE_TEMPLATE/chain_request.md
> chore: update chain ticket

- packages/react-app-revamp/config/wagmi/custom-chains/apechain.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add apechain

- packages/react-app-revamp/config/wagmi/custom-chains/fluentTestnet.ts
> chain: update fluent rpc and explorer url

- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
- packages/react-app-revamp/lib/permissioning/index.ts
> chore: update token holders message for native token

- packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
> enhancement: set demo day as default template

- packages/react-app-revamp/hooks/useDeployContest/index.ts
> chore: fetch jklabs address always from db

- packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
Closes #2945
Let's see if the decimal change for hedera chain native token closes this issue, if not, i will reopen the issue.
@siobh9 a question here, not sure if these types of changes where we change config of the chain should be prefixed with chain for the branch and labeled as chain? or this is more of a chore where we change the chain structure and we want to keep chain label only when we add chains?
> chain: update hedera native token decimals

- packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/lib/permissioning/index.ts
- packages/react-app-revamp/package.json
- packages/react-app-revamp/public/icons/copy.svg
- yarn.lock
- #2935 
- #2936 
- #2937 
- #2938 
- #2943 
- #2944 
- #2939 
- #2940 
- #2941 
- #2942 
- #2948 
- #2949 
- #2951
> patch PR 1 of week ending 11/26/24

- packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
https://www.hashgraph.com/hashio/
trying again after #2843 because we're running into issues with decimals.
> chain: update hedera rpc and decimals

- packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
> patch PR 2 of week ending 11/26/24

- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Extensions/index.tsx
> feat: add dune dashboard analytics extension

- packages/react-app-revamp/components/UI/ImageUpload/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/components/Modal/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/utils/index.ts
- packages/react-app-revamp/components/_pages/Create/components/PromptPreview/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/PromptPreviewToggle/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageLayout/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
- packages/react-app-revamp/styles/globals.css
- packages/react-app-revamp/tailwind.config.js
> feat: redesigned description page with image upload

- packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
- packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
- packages/react-app-revamp/hooks/useUser/index.ts
> chore: make all rpc calls resilient to failure

- packages/react-app-revamp/components/_pages/ListProposals/container.tsx
> patch PR 2 of week ending 12/10/24

- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/hooks/useUser/index.ts
> feat: add bridge docs when user doesn't have funds

- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
> bugfix: fix voting close functionality in timing tab of create flow

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
> chore: disable decimals in create pool

- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
> bugfix: maintain scroll position when page routing

- packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
- packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
Closes #2680
After some debugging, i realized that this was coming from `generateMetadata` function from page component, issue is that we were passing `address` as `undefined` to `getContestContractVersion` fn, which resulted in an error.
> bugfix: fix contract version not found err

- packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
- packages/react-app-revamp/hooks/useEditContestTitleAndImage/index.tsx
There was some logging leftovers from #3084, so we are just removing those in this PR.
> chore: remove logging

- packages/react-app-revamp/components/UI/Toast/components/Info/index.tsx
- packages/react-app-revamp/components/UI/Toast/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
> enhancement: add link in toast to bridge docs

- packages/react-app-revamp/components/_pages/ProposalContent/components/Profile/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
In this PR i just added a small enhancements that i've noticed in the leaderboard layout with the spacing.
> enhancement: improve leaderboard spacing

- packages/react-app-revamp/package.json
- yarn.lock
> patch PR 2 of week ending 12/24/24

- packages/react-app-revamp/hooks/useError/index.ts
- packages/react-app-revamp/utils/error.ts
> chore: update toast language for execution reverted errors

- packages/react-app-revamp/components/Header/LandingHeader/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/layouts/LayoutBase/index.tsx
> chore: add substack to footer

- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
> chore: add dune supported chain names

- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
> enhancement: remove gap between entry navigation and menu bar on mobile

- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/utils/index.ts
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
> merge sprint ending 1/14/25

- packages/react-app-revamp/config/wagmi/custom-chains/lukso.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add lukso

- packages/react-app-revamp/components/UI/ButtonV3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
> enhancement: attach enter contest btn to the bottom on mobile

- packages/react-app-revamp/config/s3/index.ts
> patch PR 2 of week ending 1/21/25

- packages/react-app-revamp/components/_pages/Create/components/TagDropdown/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTitle/index.tsx
I have noticed that dropdown chevron positioning is out of place in the tag step in create flow, additionally, contest title text got into the shared component so i removed that piece too.
> enhancement: fix dropdown chevron positioning in tag input

- packages/react-app-revamp/components/UI/Deployment/Testnet/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
> enhancement: add testnet warning in create flow

- packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
> wording: update landing page text

- packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
We are replacing all bullet points with chevron on the landing page text, i forgot to push this commit in the #3305 so adding it in this PR
> enhancement: add chevron instead of bullets on landing page text

- packages/react-app-revamp/config/wagmi/custom-chains/soneium.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add soneium

- packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
- packages/react-app-revamp/config/lens/index.ts
- packages/react-app-revamp/hooks/useProfileData/index.ts
- packages/react-app-revamp/next.config.js
closes #3055 
the lens sdk has just had progressively more issues over the course of months until it just straightup stopped importing correctly in #3340, so removing for now.
> chore: rm lens

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddFunds/index.tsx
> enhancement: add warning about voters arbing rewards pool

- packages/react-app-revamp/public/celo.svg
> chain: update celo logo

- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/index.tsx
> bugfix: add faq link to voting contest type in create contest

- packages/react-app-revamp/components/_pages/Landing/components/index.tsx
> wording: lowercase create contest button on landing page

- .github/workflows/nextjs_build.yml
- packages/react-app-revamp/app/api/brevo/send/route.ts
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddFunds/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/index.tsx
- packages/react-app-revamp/components/_pages/Landing/components/index.tsx
- packages/react-app-revamp/config/brevo/index.ts
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useEmailSend/index.ts
- packages/react-app-revamp/hooks/useEmailSignup/index.tsx
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/lib/email/index.ts
- packages/react-app-revamp/lib/email/types.ts
- packages/react-app-revamp/package.json
- packages/react-app-revamp/public/celo.svg
- yarn.lock
- #3360 
- #3361 
- #3362 
- #3367 
- #3366 
- #3365 
- #3364 
- #3356
> merge sprint ending 2/18/25

- packages/react-app-revamp/components/TokenSearchModal/ERC20/index.tsx
- packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
- packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
- packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
- packages/react-app-revamp/components/TokenSearchModal/index.tsx
- packages/react-app-revamp/components/UI/DialogModalV4/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
- packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
- packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
- packages/react-app-revamp/lib/etherscan/index.ts
- packages/react-app-revamp/lib/permissioning/index.ts
> chore: implement etherscan v2

- packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
> bugfix: fix contest duration calculation to show total days instead of remainder days

- packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
I have noticed that public rpc for sepolia does not work ( returns 400 error ) so i switched to the more stable one.
> chore: update sepolia public rpc

- packages/react-app-revamp/hooks/useProposal/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
> bugfix: fix entry sorting after submitting

- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
> bugfix: fix full description btn overflow

- packages/react-app-revamp/components/_pages/Create/components/GradientTitle/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/RadioButtonsGroup/index.tsx
- packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestEntries/components/AdditionalDescription/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestEntries/components/Preview/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/UnconnectedAccount/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotingPeriod/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/AnyoneCanPlay/config.ts
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/AnyoneCanPlay/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRadioGroup/index.tsx
> enhancement: implement create flow polishes

- packages/react-app-revamp/components/UI/GradientText/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
> enhancement: update rewards info color

- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
> enhancement: update get more token color

- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Layout/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Preview/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/art/config.ts
- packages/react-app-revamp/components/_pages/Create/templates/art/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/debate/config.ts
- packages/react-app-revamp/components/_pages/Create/templates/debate/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/demo-day/config.ts
- packages/react-app-revamp/components/_pages/Create/templates/demo-day/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/grants-round/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/hackathon/config.ts
- packages/react-app-revamp/components/_pages/Create/templates/hackathon/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/leaderboard/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/live-contest/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/meme/config.ts
- packages/react-app-revamp/components/_pages/Create/templates/meme/index.tsx
- packages/react-app-revamp/components/_pages/Create/templates/test-contest/index.tsx
- packages/react-app-revamp/helpers/textUtils.ts
- packages/react-app-revamp/hooks/useSetContestTemplate/index.ts
Closes #3435 
check out latest changes via this link - https://jokerace-qcbavwawc-jokerace.vercel.app
> enhancement: template polishes

- packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
> chore: update tag format in contest cards

- packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Navigation/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Submit/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/Table/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
- packages/react-app-revamp/components/_pages/Create/components/Buttons/Mobile/index.tsx
- packages/react-app-revamp/hooks/useDeployRewards/index.ts
Closes #3186
check out latest changes via this link https://jokerace-nre1w6r8c-jokerace.vercel.app/
> feat: implement rewards flow v4

- packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
> bugfix: enable next button after wallet is connected in monetization step

- packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Navigation/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Submit/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/Table/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/Buttons/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/custom-tweet.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/utils/markdown.tsx
- packages/react-app-revamp/hooks/useDeployRewards/index.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #3462 
- #3463 
- #3444 
- #3461 
- #3468
> merge sprint ending 3/11/25

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
> enhancement: show 5 ranks in rewards flow

- packages/react-app-revamp/tailwind.config.js
> enhancement: implement higher contrast borders for entries

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Split/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/AnyoneCanPlay/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/EntryBased/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/VotingBased/index.tsx
- packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
- packages/react-app-revamp/hooks/useChargeDetails/index.ts
- packages/react-app-revamp/hooks/useDeployContest/store.tsx
> chore: update split across the codebase and site

- packages/react-app-revamp/components/Subscribe/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
- packages/react-app-revamp/hooks/useDeployContest/index.ts
> feat: always require wallet address for email updates

- packages/react-app-revamp/config/wagmi/custom-chains/berachain.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add berachain

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
> wording: remove qualified wording on params tab

- packages/react-app-revamp/components/ChargeLayout/components/Vote/components/TotalCharge/index.tsx
- packages/react-app-revamp/components/UI/ButtonV3/index.tsx
- packages/react-app-revamp/components/_pages/DialogMaxVotesAlert/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
- packages/react-app-revamp/helpers/nativeToken.ts
- packages/react-app-revamp/helpers/totalCharge.ts
> enhancement: add warning for max votes

- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
> wording: add recommended to entry open time

- packages/react-app-revamp/components/_pages/Create/hooks/useSetContestTypeConfig.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/utils.ts
- packages/react-app-revamp/components/_pages/Create/types.ts
> enhancement: add dynamic text for summary in create flow

- packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
> bugfix: fix bsod on templates if wallet is not connected

- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Split/index.tsx
- packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
> wording: update split charges text

- packages/react-app-revamp/components/Comments/components/Comment/index.tsx
- packages/react-app-revamp/components/Comments/components/List/index.tsx
- packages/react-app-revamp/components/Comments/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Split/index.tsx
- packages/react-app-revamp/components/_pages/DialogMaxVotesAlert/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/components/VoterRow/index.tsx
- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/components/Comments/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/components/VoteFooter/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/components/VotersList/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/package.json
- yarn.lock
- #3567 
- #3580 
- #3581 
- #3566 
- #3582
> patch PR 2 of week ending 4/8/25

- packages/react-app-revamp/config/wagmi/custom-chains/unichain.ts
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
> chain: add unichain

- packages/react-app-revamp/components/Header/LandingHeader/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
- packages/react-app-revamp/config/links/index.tsx
- packages/react-app-revamp/layouts/LayoutBase/index.tsx
> chore: add privacy policy to footer

- packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/index.tsx
- packages/react-app-revamp/components/_pages/ListProposals/skeleton.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/components/_pages/Submission/components/Buttons/Delete/index.tsx
- packages/react-app-revamp/components/_pages/Submission/components/Modals/Delete/index.tsx
- packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
> feat: add ability for creator/entrant to delete entry on frontend

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
> wording: update split toggle on rewards page

- packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
> patch PR 3 of week ending 4/14/25

- packages/react-app-revamp/components/_pages/Create/components/GradientTitle/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/AdditionalDescriptionLayout/index.tsx
> enhancement: replace email signups from toggle to optional

- packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
> enhancement: display error on featured contest card

- packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
- packages/react-app-revamp/helpers/metadata.ts
> enhancement: put additional text in white bold and rm italic

- packages/react-app-revamp/config/wagmi/index.ts
> wording: guide new users to para

- packages/react-app-revamp/config/wagmi/index.ts
> patch PR 3 of week ending 4/22/25

- packages/react-app-revamp/components/_pages/Create/components/ConnectPrompt/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
- packages/react-app-revamp/helpers/getNativeTokenInfo.ts
- packages/react-app-revamp/package.json
- renovate.json
- yarn.lock
- #3677 
- #3678 
- #3690 
- #3684
- #3679
> patch PR 1 of week ending 4/29/25

- packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
- packages/react-app-revamp/components/ChargeLayout/components/Vote/components/MyVotes/index.tsx
- packages/react-app-revamp/components/Onramp/components/Card/index.tsx
- packages/react-app-revamp/components/Onramp/providers/coinbase/index.tsx
- packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
- packages/react-app-revamp/components/Voting/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Submit/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
- packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
- packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Closes #3619
I have added all polishes from the ticket (including modals to add funds in create flow & create rewards)
- Check create flow updates via this link - https://jokerace-6ubly6xg2-jokerace.vercel.app/contest/new
- Check modal for submitting an entry via this link - https://jokerace-6ubly6xg2-jokerace.vercel.app/contest/arbitrumone/0x061d6450222c3b88f1a72d8c6b365db0a31d636c
- Check voting flow (click on upvote, or click on entry itself) - https://jokerace-6ubly6xg2-jokerace.vercel.app/contest/basetestnet/0xcc94fde8672e6a28c4c8d7664342612f808e3b44
When it comes to rewards flow, you would have to create a contest and then empty that wallet from which you created a contest in order to test it.
> enhancement: add funds polishes

- packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
> chore: add berachain to dune extension

- packages/react-app-revamp/.eslintrc.json
> chore: rm eslint build error

- packages/react-app-revamp/app/not-found.tsx
> chore: rm server component error message

- packages/react-app-revamp/helpers/ethers.ts
Fixes the issue where `JsonRpcProvider` tries to detect network indefinitely by using code from here - https://github.com/ethers-io/ethers.js/issues/4377#issuecomment-2023855491
> chore: fix JsonRpcProvider retry error

- packages/react-app-revamp/components/ChargeLayout/components/Vote/components/MyVotes/index.tsx
- packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
- packages/react-app-revamp/components/Voting/index.tsx
Closes #3743
Test it with this contest - https://jokerace-fi9dv8pz6-jokerace.vercel.app/contest/arbitrumone/0x9763954880f7da64979523758c49cff9041e213a
> chore: always show add funds optional link if user has funds when voting

- packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
- packages/react-app-revamp/components/_pages/FeaturedContests/index.tsx
- packages/react-app-revamp/components/_pages/Landing/components/index.tsx
- packages/react-app-revamp/hooks/useTotalVotes/index.ts
- packages/react-app-revamp/lib/contests/constants/index.ts
- packages/react-app-revamp/lib/contests/contracts.ts
- packages/react-app-revamp/lib/contests/index.ts
- packages/react-app-revamp/lib/contests/types.ts
- packages/react-app-revamp/lib/contests/utils/streamItems.ts
- packages/react-app-revamp/lib/user/index.tsx
> patch PR 5 of week ending 5/5/25

- .github/workflows/nextjs_build.yml
- packages/react-app-revamp/components/Subscribe/index.tsx
- packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
- packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/index.tsx
- packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/config/wagmi/server.ts
- packages/react-app-revamp/config/wagmi/transports.ts
- packages/react-app-revamp/helpers/ethers.ts
- packages/react-app-revamp/helpers/getContestContractVersion.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #3798
- #3797
- #3799
- #3800
- #3766
- #3804
- #3805
- #3806
> patch PR 1 of week ending 5/13/25

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Rewards/components/Table/index.tsx
- packages/react-app-revamp/package.json
- yarn.lock
- #3932
- #3933 
- #3934
- #3938
> patch PR 2 of week ending 6/10/25

- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
> wording: update entering and voting messages in rules tab

- packages/react-app-revamp/components/_pages/Landing/components/index.tsx
- packages/react-app-revamp/lib/contests/contracts.ts
> bugfix: validate all calls for rewards on landing page

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Dropdown/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
> bugfix: prevent duplicate recipient selection in rewards

- packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Timing/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotingPeriod/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/utils.ts
> feat: frontend set period limits

- renovate.json
trying again after #4043 didn't take
> chore: disable tiptap updates pt2

- packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
> patch PR 2 of week ending 7/1/25

- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
- packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
> chore: make charges to rewards pool default

- packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/components/Split/index.tsx
closes #4121
(hopeful) completion of #4063 
will avoid these sorts of missing places to update in future with #4118
> wording: update last 70

- packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/components/Timer/index.tsx
- packages/react-app-revamp/helpers/exponentialMultiplier.ts
- packages/react-app-revamp/hooks/useCurrentPricePercentageIncrease/index.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #4115 
- #4116 
- #4125 
- #4126 
- #4127 
- #4131
> patch PR 2 of week ending 7/15/25 

- renovate.json
> chore: update no tiptap

- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsCounter/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsDisplay/index.tsx
- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useFundRewards/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
> enhancement: show total rewards in contest page marquee

- packages/react-app-revamp/components/Onramp/components/Buttons/FundFromAnotherChain/index.tsx
- packages/react-app-revamp/components/Onramp/index.tsx
> wording: add chain name to onramp modal

- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
> bugfix: fix marquee flash on contest page

- packages/react-app-revamp/helpers/exponentialMultiplier.ts
> bugfix: fix rounding issues for end price

- packages/react-app-revamp/components/_pages/Create/hooks/useSetContestTypeConfig.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/AnyoneCanPlay/config.ts
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/EntryBased/config.ts
- packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/VotingBased/config.ts
- packages/react-app-revamp/components/_pages/Create/types.ts
- packages/react-app-revamp/hooks/useDeployContest/slices/contestMonetizationSlice.ts
> enhancement: set exponential price curve as default in create flow

- packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsMarquee/index.tsx
> enhancement: add animation to vote and enter to earn marquee

- packages/react-app-revamp/config/wagmi/custom-chains/avalanche.ts
> patch PR 4 of week ending 7/28/25

- packages/react-app-revamp/config/wagmi/custom-chains/avalanche.ts
> patch PR 5 of week ending 7/28/25

- packages/react-app-revamp/components/Onramp/index.tsx
- packages/react-app-revamp/helpers/getChainLogo.ts
> enhancement: add chain logo to onramp modal

- packages/react-app-revamp/components/Onramp/index.tsx
- packages/react-app-revamp/helpers/getChainLogo.ts
> patch PR 2 of week ending 8/5/25

- packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
> bugfix: fix proposal voters layout shift and refactor to use infiniteQuery

- packages/react-app-revamp/components/Voting/index.tsx
> bugfix: fix vote button disabled state on mount

- packages/react-app-revamp/helpers/formatBalance.ts
- packages/react-app-revamp/helpers/formatNumber.ts
> enhancement: use formatNumberAbbreviated on rewards

- packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/index.tsx
- packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/utils.ts
> enhancement: edit template text for price curves

- Dockerfile
> patch 8 of week ending 8/18/25

- .github/workflows/nextjs_docker.yml
removing bc costs money and not going to be using right now because ran into really weird issues that aren't worth digging that deep into the stack into right now as outlined in #4377
> chore: rm digital ocean docker push

- packages/react-app-revamp/hooks/useCastVotes/index.ts
- packages/react-app-revamp/hooks/useContest/index.ts
- packages/react-app-revamp/hooks/useGenerateProof/index.ts
- packages/react-app-revamp/hooks/useProposalVotes/index.ts
- packages/react-app-revamp/lib/proposal/index.ts
- packages/react-app-revamp/lib/rewards/contracts/batch-operations.ts
- packages/react-app-revamp/lib/rewards/contracts/core.ts
- packages/react-app-revamp/lib/rewards/contracts/fetching.ts
- packages/react-app-revamp/lib/rewards/contracts/validation.ts
> chore: ensure resilience on errors

- README.md
> docs: rm DO docker README

- packages/forge/test/VoterRewardsModule.t.sol
update test names from changes in #4469
> chore: rename sorting tests

- packages/react-app-revamp/config/wagmi/index.ts
- packages/react-app-revamp/hooks/useSubmitProposal/index.ts
- packages/react-app-revamp/lib/email/types.ts
- packages/react-app-revamp/package.json
- yarn.lock
- #4584 
- #4585 
- #4586 
- #4587 
- #4588 
- #4589
> patch PR 1 of week ending 9/23/25 

- packages/react-app-revamp/app/globals.css
- packages/react-app-revamp/package.json
- yarn.lock
> merge sprint ending 9/30/25
